#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file_extension>"
    echo "Example: $0 jpg"
    exit 1
fi

extension="$1"
magick mogrify -format png ./*."$extension"
rm -rf ./*."$extension"
