foreground         #c2c7c4
background         #000000
background_opacity 1.0
cursor             #c2c7c4

active_tab_foreground     #0e2016
active_tab_background     #c2c7c4
inactive_tab_foreground   #c2c7c4
inactive_tab_background   #0e2016

active_border_color   #c2c7c4
inactive_border_color #0e2016
bell_border_color     #42718e

color0       #000000
color8       #5d7266
color1       #42718e
color9       #42718e
color2       #44909d
color10      #44909d
color3       #50a2ce
color11      #50a2ce
color4       #77a291
color12      #77a291
color5       #74adcd
color13      #74adcd
color6       #86cdde
color14      #86cdde
color7       #c2c7c4
color15      #c2c7c4
