foreground         #c1c3c5
background         #000000
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #0a1117
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #0a1117

active_border_color   #c1c3c5
inactive_border_color #0a1117
bell_border_color     #105a87

color0       #000000
color8       #59646d
color1       #105a87
color9       #105a87
color2       #1e809f
color10      #1e809f
color3       #30a3c3
color11      #30a3c3
color4       #46bcd3
color12      #46bcd3
color5       #73ccb1
color13      #73ccb1
color6       #7ed2dd
color14      #7ed2dd
color7       #c1c3c5
color15      #c1c3c5
