foreground         #c1c2c4
background         #000000
background_opacity 1.0
cursor             #c1c2c4

active_tab_foreground     #090b15
active_tab_background     #c1c2c4
inactive_tab_foreground   #c1c2c4
inactive_tab_background   #090b15

active_border_color   #c1c2c4
inactive_border_color #090b15
bell_border_color     #31304d

color0       #000000
color8       #585b6c
color1       #31304d
color9       #31304d
color2       #373455
color10      #373455
color3       #31394f
color11      #31394f
color4       #3f3f63
color12      #3f3f63
color5       #4c4673
color13      #4c4673
color6       #524e80
color14      #524e80
color7       #c1c2c4
color15      #c1c2c4
