return {}
-- return {
--   "VonHeikemen/lsp-zero.nvim",
--   branch = "v1.x",
--   dependencies = {
--     -- LSP Support
--     "neovim/nvim-lspconfig",             -- Required
--     "williamboman/mason.nvim",           -- Optional
--     "williamboman/mason-lspconfig.nvim", -- Optional
--
--     -- Autocompletion
--     "hrsh7th/nvim-cmp",         -- Required
--     "hrsh7th/cmp-nvim-lsp",     -- Required
--     "hrsh7th/cmp-buffer",       -- Optional
--     "hrsh7th/cmp-path",         -- Optional
--     "hrsh7th/cmp-cmdline",      -- Optional
--     "saadparwaiz1/cmp_luasnip", -- Optional
--     "hrsh7th/cmp-nvim-lua",     -- Optional
--
--     -- Snippets
--     "L3MON4D3/LuaSnip",             -- Required
--     "rafamadriz/friendly-snippets", -- Optional
--
--     -- Formatter/linter
--     "jose-elias-alvarez/null-ls.nvim",
--     "jay-babu/mason-null-ls.nvim",
--
--     -- Useful plugin needed for null-ls
--     "nvim-lua/plenary.nvim"
--   },
--   config = function()
--     local cmp = require("cmp")
--     local lsp_zero = require("lsp-zero")
--     local null_ls = require("null-ls")
--     local mason = require("mason")
--
--     ----------------------------------------
--     -- mason
--     ----------------------------------------
--     mason.setup({
--       ui = {
--         border = "rounded",
--       },
--     })
--
--     ----------------------------------------
--     -- lsp-zero
--     ----------------------------------------
--     lsp_zero.preset({
--       name = "minimal",
--       set_lsp_keymaps = true,
--       manage_nvim_cmp = true,
--       suggest_lsp_servers = true,
--     })
--
--     lsp_zero.nvim_workspace()
--
--     lsp_zero.set_preferences({
--       sign_icons = {
--         error = "",
--         warn = "",
--         hint = "",
--         info = "",
--       }
--     })
--
--     lsp_zero.ensure_installed({
--       "arduino_language_server",
--       "clangd",
--       "cmake",
--       "cssls",
--       "html",
--       "jdtls",
--       "tsserver",
--       "ltex",
--       "lua_ls",
--       "marksman",
--       "pyright",
--       "rust_analyzer",
--       "tailwindcss",
--     })
--
--
--     vim.diagnostic.config({
--       virtual_text = {
--         prefix = "",
--       }
--     })
--
--     ----------------------------------------
--     -- cmp
--     ----------------------------------------
--     local cmp_config = lsp_zero.defaults.cmp_config({
--       window = {
--         completion = {
--           border = "rounded",
--         },
--         documentation = {
--           border = "rounded",
--         },
--       },
--     })
--
--     cmp.setup(cmp_config)
--
--     ----------------------------------------
--     -- nul-ls
--     ----------------------------------------
--     local null_opts = lsp_zero.build_options("null-ls", {
--       on_attach = function(client)
--         if client.server_capabilities.document_formatting then
--           vim.api.nvim_create_autocmd("BufWritePre", {
--             desc = "Auto format before save",
--             pattern = "<buffer>",
--             callback = vim.lsp.buf.format,
--           })
--         end
--       end
--     })
--
--     null_ls.setup({
--       on_attach = null_opts.on_attach,
--       sources = {
--         -- TODO add sources
--         null_ls.builtins.formatting.stylua,
--       }
--     })
--     lsp_zero.setup()
--   end
-- }
