return {}
-- return {
--   "epwalsh/obsidian.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   config = function()
--     require("obsidian").setup({
--       dir = "~/neorg",
--       completion = {
--         nvim_cmp = true, -- if using nvim-cmp, otherwise set to false
--       },
--     })
--   end,
-- }
