color0 #14130e
color1 #ffb4ab
color2 #d5c951
color3 #cdc7a3
color4 #a6d0b9
color5 #d5c951
color6 #cdc7a3
color7 #e6e2d9
color8 #949181
color9 #ffb4ab
color10 #d5c951
color11 #cdc7a3
color12 #a6d0b9
color13 #d5c951
color14 #cdc7a3
color15 #e6e2d9

cursor                #e6e2d9
cursor_text_color     #14130e
background            #14130e
foreground            #e6e2d9
selection_foreground  #cbc7b5
selection_background  #49473a
active_border_color   #d5c951
inactive_border_color #49473a
url_color             #d5c951

active_tab_foreground   #363100
active_tab_background   #d5c951
inactive_tab_foreground #cbc7b5
inactive_tab_background #49473a
cursor_trail_color      #cbc7b5
