color0 #17130e
color1 #ffb4ab
color2 #ffb960
color3 #dfc2a2
color4 #bbcd9e
color5 #ffb960
color6 #dfc2a2
color7 #ebe1d9
color8 #9c8e81
color9 #ffb4ab
color10 #ffb960
color11 #dfc2a2
color12 #bbcd9e
color13 #ffb960
color14 #dfc2a2
color15 #ebe1d9

cursor                #ebe1d9
cursor_text_color     #17130e
background            #17130e
foreground            #ebe1d9
selection_foreground  #d4c4b5
selection_background  #504539
active_border_color   #ffb960
inactive_border_color #504539
url_color             #ffb960

active_tab_foreground   #472a00
active_tab_background   #ffb960
inactive_tab_foreground #d4c4b5
inactive_tab_background #504539
cursor_trail_color      #d4c4b5
