color0 #17120f
color1 #ffb4ab
color2 #ffb781
color3 #e4bfa7
color4 #c7ca95
color5 #ffb781
color6 #e4bfa7
color7 #ece0da
color8 #9f8d82
color9 #ffb4ab
color10 #ffb781
color11 #e4bfa7
color12 #c7ca95
color13 #ffb781
color14 #e4bfa7
color15 #ece0da

cursor                #ece0da
cursor_text_color     #17120f
background            #17120f
foreground            #ece0da
selection_foreground  #d6c3b7
selection_background  #52443b
active_border_color   #ffb781
inactive_border_color #52443b
url_color             #ffb781

active_tab_foreground   #4e2600
active_tab_background   #ffb781
inactive_tab_foreground #d6c3b7
inactive_tab_background #52443b
cursor_trail_color      #d6c3b7
