#!/usr/bin/env bash
set -euo pipefail

# Run wal with the provided image
wal -i "$1" -b 000000

wal_cache="${HOME}/.cache/wal/wal"

# Run hpaper with the wallpaper path from wal
hpaper start "$(< "$wal_cache")"
