#!/usr/bin/env bash

set -euo pipefail

SRC="$HOME/.config/hypr/current_wallpaper"
DEST="/usr/share/sddm/themes/Sugar-Candy/current_wallpaper"

if [[ -f "$SRC" && -f "$DEST" ]]; then
  echo "Changing SDDM wallpaper..."
  sudo cp "$SRC" "$DEST"
  sudo chmod 644 "$DEST"
fi

systemctl reboot
