# src = ttps://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/hypr/conf/windowrules/default.conf
# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# have waypaper open as a floating window in the center
windowrule = maximize 1, class:waypaper

windowrule = tile 1, title:^(Microsoft-edge)$
windowrule = tile 1, title:^(Brave-browser)$
windowrule = tile 1, title:^(Chromium)$
windowrule = float 1, title:^(pavucontrol)$
windowrule = float 1, title:^(blueman-manager)$
windowrule = float 1, title:^(nm-connection-editor)$
windowrule = float 1, title:^(qalculate-gtk)$

# i like it when kitty is semi-transparent
windowrule = opacity 0.85 override, class:^(kitty)$

# Browser Picture in Picture
windowrule = float 1, title:^(Picture-in-Picture)$
windowrule = pin 1, title:^(Picture-in-Picture)$
windowrule = move 69.5% 4%, title:^(Picture-in-Picture)$

# idleinhibit
windowrule = idle_inhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen
