-- src = https://github.com/mylinuxforwork/dotfiles/blob/main/share/dotfiles/.config/hypr/conf/windows/default.conf
-- -----------------------------------------------------
-- General window layout and colors
-- name: "Default"
-- -----------------------------------------------------

-- colors-hyprland.conf is regenerated by `wal` in old hyprlang format ($color11 = ...)
-- every time the wallpaper changes, so it can't be require()'d as a Lua module.
-- Parse it as plain text instead and keep wal-wallpaper-watch.sh untouched.
local function readWalColor(name)
  local path = os.getenv("HOME") .. "/.cache/wal/colors-hyprland.conf"
  local f = io.open(path, "r")
  if not f then return nil end
  local pattern = "^%$" .. name .. "%s*=%s*(.+)$"
  for line in f:lines() do
    local val = line:match(pattern)
    if val then f:close(); return val end
  end
  f:close()
end

local activeBorder = readWalColor("color11") or "0xffffffff"
local inactiveBorder = readWalColor("color8") or "0xff444444"

hl.config({
  general = {
    gaps_in = 1,
    gaps_out = 1,
    border_size = 3,
    layout = "dwindle",
    resize_on_border = true,
    col = {
      active_border = activeBorder,
      inactive_border = inactiveBorder,
    },
  },
})
