local utils = require("helpers.tex.utils")

return
  {
    s(
      {
        trig="\\\\",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \\
        <>
        ]],
        {
          i(0),
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="__",
        snippetType="autosnippet",
      },
      fmta(
        [[
        _{<>}<>
        ]],
        {
          i(1),
          i(0),
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="tt",
        dscr="Expands 'tt' into '\text{}'",
        snippetType="autosnippet",
      },
      fmta(
        [[
          \text{<>}<>
        ]],
        {
          i(1),
          i(0),
        }
      ),
      {
        condition=utils.in_mathzone
      }
    ),

    s(
      {
        trig="text",
        snippetType="autosnippet",
      },
      fmta(
        [[
          \text{<>}<>
        ]],
        {
          i(1),
          i(0),
        }
      ),
      {
        condition=utils.in_mathzone
      }
    ),

    s(
      {
        trig="ff",
        dscr="Expands 'ff' into '\frac{}{}'",
        snippetType="autosnippet",
      },
      fmta(
        [[
          \frac{<>}{<>}<>
        ]],
        {
          i(1),
          i(2),
          i(0)
        }
      ),
      {
        condition=utils.in_mathzone
      }
    ),

    s(
      {
        trig="frac",
        snippetType="autosnippet",
      },
      fmta(
        [[
          \frac{<>}{<>}<>
        ]],
        {
          i(1),
          i(2),
          i(0),
        }
      ),
      {
        condition=utils.in_mathzone
      }
    ),
  }
