local utils = require("helpers.tex.utils")

return
  {
    s(
      {
        trig="vec",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \vec{<>}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="norm",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \left|\left|\vec{<>}\right|\right|<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

-- TODO
    -- JUST MAKE THEM ALL MAT
    s(
      {
        trig="mat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{<>matrix}
        <>
        \end{<>matrix}<>
        ]],
        {
          i(1),
          i(2),
          rep(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="pmat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{pmatrix}
        <>
        \end{pmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="bmat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{bmatrix}
        <>
        \end{bmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="Bmat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{Bmatrix}
        <>
        \end{Bmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="vmat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{vmatrix}
        <>
        \end{vmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="Vmat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{Vmatrix}
        <>
        \end{Vmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="smat",
        snippetType="autosnippet",
      },
      fmta(
        [[
        \begin{smallmatrix}
        <>
        \end{smallmatrix}<>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    ),

    s(
      {
        trig="det",
        snippetType="autosnippet"
      },
      fmta(
        [[
        \det\left({<>}\right) <>
        ]],
        {
          i(1),
          i(0)
        }
      ),
      {condition=utils.in_mathzone}
    )
  }

