[colors]
background = '#0000008e'
black = '#000000'
blue = '#6DBFC4'
cursor = '#c7cbcb'
cyan = '#9BA5A0'
foreground = '#c7cbcb'
green = '#DDA8AA'
magenta = '#9BC6BA'
red = '#D6BEC1'
tabs = '#c7cbcb'
tabs-active = '#A4D5CD'
white = '#c7cbcb'
yellow = '#c7cbcb'
dim-black = '#0000008e'
dim-blue = '#6DBFC48e'
dim-cyan = '#9BA5A08e'
dim-foreground = '#c7cbcb8e'
dim-green = '#DDA8AA8e'
dim-magenta = '#9BC6BA8e'
dim-red = '#D6BEC18e'
dim-white = '#A4D5CD8e'
dim-yellow = '#c7cbcb8e'
light-black = '#6DBFC4'
light-blue = '#9BA5A0'
light-cyan = '#DDA8AA'
light-foreground = '#9BC6BA'
light-green = '#D6BEC1'
light-magenta = '#A4D5CD'
light-red = '#c7cbcb'
light-white = '#6DBFC4'
light-yellow = '#9BA5A0'
