--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/demon-slayer.jpg"

-- Special
background="#000000"
foreground="#c2c4c6"
cursor="#c2c4c6"

-- Colors
color0="#000000"
color1="#615453"
color2="#A25836"
color3="#9E6B4F"
color4="#D9A058"
color5="#D6B760"
color6="#7A7581"
color7="#c2c4c6"
color8="#5c6370"
color9="#615453"
color10="#A25836"
color11="#9E6B4F"
color12="#D9A058"
color13="#D6B760"
color14="#7A7581"
color15="#c2c4c6"
