[colors.primary]
background = "#000000"
foreground = "#c2c7c4"

[colors.cursor]
text = "#000000"
cursor = "#c2c7c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c7c4"

[colors.search.matches]
foreground = "#000000"
background = "#c2c7c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c7165"
background = "#c2c7c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#9EB85C"
green = "#57748E"
yellow = "#6F8D9F"
blue = "#35B7FC"
magenta = "#5BB5F6"
cyan = "#6DC0F6"
white = "#c2c7c4"

[colors.bright]
black = "#5c7165"
red = "#9EB85C"
green = "#57748E"
yellow = "#6F8D9F"
blue = "#35B7FC"
magenta = "#5BB5F6"
cyan = "#6DC0F6"
white = "#c2c7c4"

[colors.dim]
black = "#c2c7c4"
red = "#9EB85C"
green = "#5BB5F6"
yellow = "#6F8D9F"
blue = "#35B7FC"
magenta = "#57748E"
cyan = "#6DC0F6"
white = "#5c7165"

