[colors.primary]
background = "#000000"
foreground = "#c3c4c9"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c9"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c9"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606276"
background = "#c3c4c9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#667BC3"
green = "#9470A7"
yellow = "#7A83B5"
blue = "#7388D1"
magenta = "#7E92E1"
cyan = "#D1A0BB"
white = "#c3c4c9"

[colors.bright]
black = "#606276"
red = "#667BC3"
green = "#9470A7"
yellow = "#7A83B5"
blue = "#7388D1"
magenta = "#7E92E1"
cyan = "#D1A0BB"
white = "#c3c4c9"

[colors.dim]
black = "#c3c4c9"
red = "#667BC3"
green = "#7E92E1"
yellow = "#7A83B5"
blue = "#7388D1"
magenta = "#9470A7"
cyan = "#D1A0BB"
white = "#606276"

