[colors]
background = '#0000008e'
black = '#000000'
blue = '#556E9C'
cursor = '#c4c5ca'
cyan = '#937989'
foreground = '#c4c5ca'
green = '#F5628D'
magenta = '#459FD0'
red = '#9D8896'
tabs = '#c4c5ca'
tabs-active = '#DCABA9'
white = '#c4c5ca'
yellow = '#c4c5ca'
dim-black = '#0000008e'
dim-blue = '#556E9C8e'
dim-cyan = '#9379898e'
dim-foreground = '#c4c5ca8e'
dim-green = '#F5628D8e'
dim-magenta = '#459FD08e'
dim-red = '#9D88968e'
dim-white = '#DCABA98e'
dim-yellow = '#c4c5ca8e'
light-black = '#556E9C'
light-blue = '#937989'
light-cyan = '#F5628D'
light-foreground = '#459FD0'
light-green = '#9D8896'
light-magenta = '#DCABA9'
light-red = '#c4c5ca'
light-white = '#556E9C'
light-yellow = '#937989'
