# Shell variables
# Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/938937-2560x1440-desktop-hd-makoto-shinkai-background-image.jpg"

# Special
background='#000000'
foreground='#c2c3c6'
cursor='#c2c3c6'

# Colors
color0='#000000'
color1='#5B525C'
color2='#9F6553'
color3='#D19D6B'
color4='#2F53A5'
color5='#9B5FAC'
color6='#52A4E4'
color7='#c2c3c6'
color8='#5c5f70'
color9='#5B525C'
color10='#9F6553'
color11='#D19D6B'
color12='#2F53A5'
color13='#9B5FAC'
color14='#52A4E4'
color15='#c2c3c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
