[colors]
background = '#0000008e'
black = '#000000'
blue = '#646487'
cursor = '#c2c3c6'
cyan = '#8F768B'
foreground = '#c2c3c6'
green = '#837796'
magenta = '#C2A5A6'
red = '#DCACA9'
tabs = '#c2c3c6'
tabs-active = '#ECD7CF'
white = '#c2c3c6'
yellow = '#c2c3c6'
dim-black = '#0000008e'
dim-blue = '#6464878e'
dim-cyan = '#8F768B8e'
dim-foreground = '#c2c3c68e'
dim-green = '#8377968e'
dim-magenta = '#C2A5A68e'
dim-red = '#DCACA98e'
dim-white = '#ECD7CF8e'
dim-yellow = '#c2c3c68e'
light-black = '#646487'
light-blue = '#8F768B'
light-cyan = '#837796'
light-foreground = '#C2A5A6'
light-green = '#DCACA9'
light-magenta = '#ECD7CF'
light-red = '#c2c3c6'
light-white = '#646487'
light-yellow = '#8F768B'
