[colors]
background = '#0000008e'
black = '#000000'
blue = '#9EB85C'
cursor = '#c2c7c4'
cyan = '#57748E'
foreground = '#c2c7c4'
green = '#6F8D9F'
magenta = '#35B7FC'
red = '#5BB5F6'
tabs = '#c2c7c4'
tabs-active = '#6DC0F6'
white = '#c2c7c4'
yellow = '#c2c7c4'
dim-black = '#0000008e'
dim-blue = '#9EB85C8e'
dim-cyan = '#57748E8e'
dim-foreground = '#c2c7c48e'
dim-green = '#6F8D9F8e'
dim-magenta = '#35B7FC8e'
dim-red = '#5BB5F68e'
dim-white = '#6DC0F68e'
dim-yellow = '#c2c7c48e'
light-black = '#9EB85C'
light-blue = '#57748E'
light-cyan = '#6F8D9F'
light-foreground = '#35B7FC'
light-green = '#5BB5F6'
light-magenta = '#6DC0F6'
light-red = '#c2c7c4'
light-white = '#9EB85C'
light-yellow = '#57748E'
