[colors.primary]
background = "#000000"
foreground = "#c1c1c5"

[colors.cursor]
text = "#000000"
cursor = "#c1c1c5"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c1c5"

[colors.search.matches]
foreground = "#000000"
background = "#c1c1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59596d"
background = "#c1c1c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#505065"
green = "#535267"
yellow = "#6E6678"
blue = "#82727C"
magenta = "#7D7181"
cyan = "#887988"
white = "#c1c1c5"

[colors.bright]
black = "#59596d"
red = "#505065"
green = "#535267"
yellow = "#6E6678"
blue = "#82727C"
magenta = "#7D7181"
cyan = "#887988"
white = "#c1c1c5"

[colors.dim]
black = "#c1c1c5"
red = "#505065"
green = "#7D7181"
yellow = "#6E6678"
blue = "#82727C"
magenta = "#535267"
cyan = "#887988"
white = "#59596d"

