[colors.primary]
background = "#000000"
foreground = "#c4c6cc"

[colors.cursor]
text = "#000000"
cursor = "#c4c6cc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c6cc"

[colors.search.matches]
foreground = "#000000"
background = "#c4c6cc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#646b7b"
background = "#c4c6cc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#AC9472"
green = "#225BA1"
yellow = "#2857B2"
blue = "#5F66A0"
magenta = "#946D9D"
cyan = "#4B94C8"
white = "#c4c6cc"

[colors.bright]
black = "#646b7b"
red = "#AC9472"
green = "#225BA1"
yellow = "#2857B2"
blue = "#5F66A0"
magenta = "#946D9D"
cyan = "#4B94C8"
white = "#c4c6cc"

[colors.dim]
black = "#c4c6cc"
red = "#AC9472"
green = "#946D9D"
yellow = "#2857B2"
blue = "#5F66A0"
magenta = "#225BA1"
cyan = "#4B94C8"
white = "#646b7b"

