[colors.primary]
background = "#000000"
foreground = "#c8cccc"

[colors.cursor]
text = "#000000"
cursor = "#c8cccc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c8cccc"

[colors.search.matches]
foreground = "#000000"
background = "#c8cccc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a827e"
background = "#c8cccc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#1399AF"
green = "#2C9FA9"
yellow = "#62AFA6"
blue = "#7EC1AE"
magenta = "#8BBCAA"
cyan = "#C8AC8A"
white = "#c8cccc"

[colors.bright]
black = "#6a827e"
red = "#1399AF"
green = "#2C9FA9"
yellow = "#62AFA6"
blue = "#7EC1AE"
magenta = "#8BBCAA"
cyan = "#C8AC8A"
white = "#c8cccc"

[colors.dim]
black = "#c8cccc"
red = "#1399AF"
green = "#8BBCAA"
yellow = "#62AFA6"
blue = "#7EC1AE"
magenta = "#2C9FA9"
cyan = "#C8AC8A"
white = "#6a827e"

