[colors]
background = '#0000008e'
black = '#000000'
blue = '#D65F39'
cursor = '#c3c3c3'
cyan = '#9D6A4F'
foreground = '#c3c3c3'
green = '#C89548'
magenta = '#DFA05A'
red = '#FADD70'
tabs = '#c3c3c3'
tabs-active = '#668EAB'
white = '#c3c3c3'
yellow = '#c3c3c3'
dim-black = '#0000008e'
dim-blue = '#D65F398e'
dim-cyan = '#9D6A4F8e'
dim-foreground = '#c3c3c38e'
dim-green = '#C895488e'
dim-magenta = '#DFA05A8e'
dim-red = '#FADD708e'
dim-white = '#668EAB8e'
dim-yellow = '#c3c3c38e'
light-black = '#D65F39'
light-blue = '#9D6A4F'
light-cyan = '#C89548'
light-foreground = '#DFA05A'
light-green = '#FADD70'
light-magenta = '#668EAB'
light-red = '#c3c3c3'
light-white = '#D65F39'
light-yellow = '#9D6A4F'
