[colors]
background = '#0000008e'
black = '#000000'
blue = '#026958'
cursor = '#c1c4c5'
cyan = '#01536E'
foreground = '#c1c4c5'
green = '#01647B'
magenta = '#028F76'
red = '#016988'
tabs = '#c1c4c5'
tabs-active = '#026799'
white = '#c1c4c5'
yellow = '#c1c4c5'
dim-black = '#0000008e'
dim-blue = '#0269588e'
dim-cyan = '#01536E8e'
dim-foreground = '#c1c4c58e'
dim-green = '#01647B8e'
dim-magenta = '#028F768e'
dim-red = '#0169888e'
dim-white = '#0267998e'
dim-yellow = '#c1c4c58e'
light-black = '#026958'
light-blue = '#01536E'
light-cyan = '#01647B'
light-foreground = '#028F76'
light-green = '#016988'
light-magenta = '#026799'
light-red = '#c1c4c5'
light-white = '#026958'
light-yellow = '#01536E'
