[colors]
background = '#0000008e'
black = '#000000'
blue = '#5B525C'
cursor = '#c2c3c6'
cyan = '#9F6553'
foreground = '#c2c3c6'
green = '#D19D6B'
magenta = '#2F53A5'
red = '#9B5FAC'
tabs = '#c2c3c6'
tabs-active = '#52A4E4'
white = '#c2c3c6'
yellow = '#c2c3c6'
dim-black = '#0000008e'
dim-blue = '#5B525C8e'
dim-cyan = '#9F65538e'
dim-foreground = '#c2c3c68e'
dim-green = '#D19D6B8e'
dim-magenta = '#2F53A58e'
dim-red = '#9B5FAC8e'
dim-white = '#52A4E48e'
dim-yellow = '#c2c3c68e'
light-black = '#5B525C'
light-blue = '#9F6553'
light-cyan = '#D19D6B'
light-foreground = '#2F53A5'
light-green = '#9B5FAC'
light-magenta = '#52A4E4'
light-red = '#c2c3c6'
light-white = '#5B525C'
light-yellow = '#9F6553'
