foreground         #c7c2c3
background         #000000
background_opacity 1.0
cursor             #c7c2c3

active_tab_foreground     #000000
active_tab_background     #c7c2c3
inactive_tab_foreground   #c7c2c3
inactive_tab_background   #000000

active_border_color   #c7c2c3
inactive_border_color #000000
bell_border_color     #E27051

color0       #000000
color8       #725d5f
color1       #E27051
color9       #E27051
color2       #F09863
color10      #F09863
color3       #F6CA40
color11      #F6CA40
color4       #AC6F87
color12      #AC6F87
color5       #B29C9F
color13      #B29C9F
color6       #EDAB92
color14      #EDAB92
color7       #c7c2c3
color15      #c7c2c3
