[colors]
background = '#0000008e'
black = '#000000'
blue = '#3272A9'
cursor = '#c6cacf'
cyan = '#3894BD'
foreground = '#c6cacf'
green = '#15A2D9'
magenta = '#28CBF4'
red = '#5DD3F4'
tabs = '#c6cacf'
tabs-active = '#9EA7B9'
white = '#c6cacf'
yellow = '#c6cacf'
dim-black = '#0000008e'
dim-blue = '#3272A98e'
dim-cyan = '#3894BD8e'
dim-foreground = '#c6cacf8e'
dim-green = '#15A2D98e'
dim-magenta = '#28CBF48e'
dim-red = '#5DD3F48e'
dim-white = '#9EA7B98e'
dim-yellow = '#c6cacf8e'
light-black = '#3272A9'
light-blue = '#3894BD'
light-cyan = '#15A2D9'
light-foreground = '#28CBF4'
light-green = '#5DD3F4'
light-magenta = '#9EA7B9'
light-red = '#c6cacf'
light-white = '#3272A9'
light-yellow = '#3894BD'
