[colors.primary]
background = "#000000"
foreground = "#c3c4c7"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c7"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6572"
background = "#c3c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#4C4C56"
green = "#5C5D6A"
yellow = "#936F6E"
blue = "#A6867A"
magenta = "#335D84"
cyan = "#556E90"
white = "#c3c4c7"

[colors.bright]
black = "#5e6572"
red = "#4C4C56"
green = "#5C5D6A"
yellow = "#936F6E"
blue = "#A6867A"
magenta = "#335D84"
cyan = "#556E90"
white = "#c3c4c7"

[colors.dim]
black = "#c3c4c7"
red = "#4C4C56"
green = "#335D84"
yellow = "#936F6E"
blue = "#A6867A"
magenta = "#5C5D6A"
cyan = "#556E90"
white = "#5e6572"

