[colors.primary]
background = "#000000"
foreground = "#c7cbcb"

[colors.cursor]
text = "#000000"
cursor = "#c7cbcb"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c7cbcb"

[colors.search.matches]
foreground = "#000000"
background = "#c7cbcb"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#687f7f"
background = "#c7cbcb"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#6DBFC4"
green = "#9BA5A0"
yellow = "#DDA8AA"
blue = "#9BC6BA"
magenta = "#D6BEC1"
cyan = "#A4D5CD"
white = "#c7cbcb"

[colors.bright]
black = "#687f7f"
red = "#6DBFC4"
green = "#9BA5A0"
yellow = "#DDA8AA"
blue = "#9BC6BA"
magenta = "#D6BEC1"
cyan = "#A4D5CD"
white = "#c7cbcb"

[colors.dim]
black = "#c7cbcb"
red = "#6DBFC4"
green = "#D6BEC1"
yellow = "#DDA8AA"
blue = "#9BC6BA"
magenta = "#9BA5A0"
cyan = "#A4D5CD"
white = "#687f7f"

