[colors.primary]
background = "#000000"
foreground = "#c4c3c6"

[colors.cursor]
text = "#000000"
cursor = "#c4c3c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c3c6"

[colors.search.matches]
foreground = "#000000"
background = "#c4c3c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#605d71"
background = "#c4c3c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#F05B9A"
green = "#F730F5"
yellow = "#F461ED"
blue = "#69A6F3"
magenta = "#FC9F99"
cyan = "#B4B8E0"
white = "#c4c3c6"

[colors.bright]
black = "#605d71"
red = "#F05B9A"
green = "#F730F5"
yellow = "#F461ED"
blue = "#69A6F3"
magenta = "#FC9F99"
cyan = "#B4B8E0"
white = "#c4c3c6"

[colors.dim]
black = "#c4c3c6"
red = "#F05B9A"
green = "#FC9F99"
yellow = "#F461ED"
blue = "#69A6F3"
magenta = "#F730F5"
cyan = "#B4B8E0"
white = "#605d71"

