[colors]
background = '#0000008e'
black = '#000000'
blue = '#485157'
cursor = '#c2c4c7'
cyan = '#58646B'
foreground = '#c2c4c7'
green = '#9E6526'
magenta = '#6B9F73'
red = '#D3AB3E'
tabs = '#c2c4c7'
tabs-active = '#697A85'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0000008e'
dim-blue = '#4851578e'
dim-cyan = '#58646B8e'
dim-foreground = '#c2c4c78e'
dim-green = '#9E65268e'
dim-magenta = '#6B9F738e'
dim-red = '#D3AB3E8e'
dim-white = '#697A858e'
dim-yellow = '#c2c4c78e'
light-black = '#485157'
light-blue = '#58646B'
light-cyan = '#9E6526'
light-foreground = '#6B9F73'
light-green = '#D3AB3E'
light-magenta = '#697A85'
light-red = '#c2c4c7'
light-white = '#485157'
light-yellow = '#58646B'
