[colors]
background = '#0000008e'
black = '#000000'
blue = '#AB674E'
cursor = '#c3c6c6'
cyan = '#548654'
foreground = '#c3c6c6'
green = '#6B8D66'
magenta = '#A0996D'
red = '#547588'
tabs = '#c3c6c6'
tabs-active = '#609BA5'
white = '#c3c6c6'
yellow = '#c3c6c6'
dim-black = '#0000008e'
dim-blue = '#AB674E8e'
dim-cyan = '#5486548e'
dim-foreground = '#c3c6c68e'
dim-green = '#6B8D668e'
dim-magenta = '#A0996D8e'
dim-red = '#5475888e'
dim-white = '#609BA58e'
dim-yellow = '#c3c6c68e'
light-black = '#AB674E'
light-blue = '#548654'
light-cyan = '#6B8D66'
light-foreground = '#A0996D'
light-green = '#547588'
light-magenta = '#609BA5'
light-red = '#c3c6c6'
light-white = '#AB674E'
light-yellow = '#548654'
