[colors]
background = '#0000008e'
black = '#000000'
blue = '#C1AAAF'
cursor = '#cbcdd0'
cyan = '#96B4CE'
foreground = '#cbcdd0'
green = '#AAD3EA'
magenta = '#F7DACC'
red = '#FEE7D4'
tabs = '#cbcdd0'
tabs-active = '#CED6E2'
white = '#cbcdd0'
yellow = '#cbcdd0'
dim-black = '#0000008e'
dim-blue = '#C1AAAF8e'
dim-cyan = '#96B4CE8e'
dim-foreground = '#cbcdd08e'
dim-green = '#AAD3EA8e'
dim-magenta = '#F7DACC8e'
dim-red = '#FEE7D48e'
dim-white = '#CED6E28e'
dim-yellow = '#cbcdd08e'
light-black = '#C1AAAF'
light-blue = '#96B4CE'
light-cyan = '#AAD3EA'
light-foreground = '#F7DACC'
light-green = '#FEE7D4'
light-magenta = '#CED6E2'
light-red = '#cbcdd0'
light-white = '#C1AAAF'
light-yellow = '#96B4CE'
