[colors]
background = '#0000008e'
black = '#000000'
blue = '#696053'
cursor = '#c6c7c2'
cyan = '#915C39'
foreground = '#c6c7c2'
green = '#8E6C56'
magenta = '#A2926B'
red = '#D0AB6B'
tabs = '#c6c7c2'
tabs-active = '#5C7583'
white = '#c6c7c2'
yellow = '#c6c7c2'
dim-black = '#0000008e'
dim-blue = '#6960538e'
dim-cyan = '#915C398e'
dim-foreground = '#c6c7c28e'
dim-green = '#8E6C568e'
dim-magenta = '#A2926B8e'
dim-red = '#D0AB6B8e'
dim-white = '#5C75838e'
dim-yellow = '#c6c7c28e'
light-black = '#696053'
light-blue = '#915C39'
light-cyan = '#8E6C56'
light-foreground = '#A2926B'
light-green = '#D0AB6B'
light-magenta = '#5C7583'
light-red = '#c6c7c2'
light-white = '#696053'
light-yellow = '#915C39'
