[colors.primary]
background = "#000000"
foreground = "#c7cbcc"

[colors.cursor]
text = "#000000"
cursor = "#c7cbcc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c7cbcc"

[colors.search.matches]
foreground = "#000000"
background = "#c7cbcc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#687d7f"
background = "#c7cbcc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#68CAFC"
green = "#B3ADA8"
yellow = "#F3A0A5"
blue = "#E7D2A6"
magenta = "#A1DBF9"
cyan = "#EFDCD6"
white = "#c7cbcc"

[colors.bright]
black = "#687d7f"
red = "#68CAFC"
green = "#B3ADA8"
yellow = "#F3A0A5"
blue = "#E7D2A6"
magenta = "#A1DBF9"
cyan = "#EFDCD6"
white = "#c7cbcc"

[colors.dim]
black = "#c7cbcc"
red = "#68CAFC"
green = "#A1DBF9"
yellow = "#F3A0A5"
blue = "#E7D2A6"
magenta = "#B3ADA8"
cyan = "#EFDCD6"
white = "#687d7f"

