[colors.primary]
background = "#000000"
foreground = "#c8c6ca"

[colors.cursor]
text = "#000000"
cursor = "#c8c6ca"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c8c6ca"

[colors.search.matches]
foreground = "#000000"
background = "#c8c6ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6f657b"
background = "#c8c6ca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#274D8E"
green = "#2962A9"
yellow = "#486098"
blue = "#1F76D4"
magenta = "#90718B"
cyan = "#2599DF"
white = "#c8c6ca"

[colors.bright]
black = "#6f657b"
red = "#274D8E"
green = "#2962A9"
yellow = "#486098"
blue = "#1F76D4"
magenta = "#90718B"
cyan = "#2599DF"
white = "#c8c6ca"

[colors.dim]
black = "#c8c6ca"
red = "#274D8E"
green = "#90718B"
yellow = "#486098"
blue = "#1F76D4"
magenta = "#2962A9"
cyan = "#2599DF"
white = "#6f657b"

