[colors]
background = '#0000008e'
black = '#000000'
blue = '#39445C'
cursor = '#c3c3c6'
cyan = '#3E4A63'
foreground = '#c3c3c6'
green = '#43425E'
magenta = '#4E4A77'
red = '#4A637D'
tabs = '#c3c3c6'
tabs-active = '#555384'
white = '#c3c3c6'
yellow = '#c3c3c6'
dim-black = '#0000008e'
dim-blue = '#39445C8e'
dim-cyan = '#3E4A638e'
dim-foreground = '#c3c3c68e'
dim-green = '#43425E8e'
dim-magenta = '#4E4A778e'
dim-red = '#4A637D8e'
dim-white = '#5553848e'
dim-yellow = '#c3c3c68e'
light-black = '#39445C'
light-blue = '#3E4A63'
light-cyan = '#43425E'
light-foreground = '#4E4A77'
light-green = '#4A637D'
light-magenta = '#555384'
light-red = '#c3c3c6'
light-white = '#39445C'
light-yellow = '#3E4A63'
