[colors.primary]
background = "#000000"
foreground = "#c6cfc8"

[colors.cursor]
text = "#000000"
cursor = "#c6cfc8"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6cfc8"

[colors.search.matches]
foreground = "#000000"
background = "#c6cfc8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6b826f"
background = "#c6cfc8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#506F93"
green = "#A66886"
yellow = "#619BA0"
blue = "#49ACB7"
magenta = "#5FAADA"
cyan = "#97A69F"
white = "#c6cfc8"

[colors.bright]
black = "#6b826f"
red = "#506F93"
green = "#A66886"
yellow = "#619BA0"
blue = "#49ACB7"
magenta = "#5FAADA"
cyan = "#97A69F"
white = "#c6cfc8"

[colors.dim]
black = "#c6cfc8"
red = "#506F93"
green = "#5FAADA"
yellow = "#619BA0"
blue = "#49ACB7"
magenta = "#A66886"
cyan = "#97A69F"
white = "#6b826f"

