[colors]
background = '#0000008e'
black = '#000000'
blue = '#C49171'
cursor = '#c7c2c7'
cyan = '#36548D'
foreground = '#c7c2c7'
green = '#636C90'
magenta = '#9A7887'
red = '#C17F82'
tabs = '#c7c2c7'
tabs-active = '#6F92B2'
white = '#c7c2c7'
yellow = '#c7c2c7'
dim-black = '#0000008e'
dim-blue = '#C491718e'
dim-cyan = '#36548D8e'
dim-foreground = '#c7c2c78e'
dim-green = '#636C908e'
dim-magenta = '#9A78878e'
dim-red = '#C17F828e'
dim-white = '#6F92B28e'
dim-yellow = '#c7c2c78e'
light-black = '#C49171'
light-blue = '#36548D'
light-cyan = '#636C90'
light-foreground = '#9A7887'
light-green = '#C17F82'
light-magenta = '#6F92B2'
light-red = '#c7c2c7'
light-white = '#C49171'
light-yellow = '#36548D'
