[colors.primary]
background = "#000000"
foreground = "#c8cbcf"

[colors.cursor]
text = "#000000"
cursor = "#c8cbcf"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c8cbcf"

[colors.search.matches]
foreground = "#000000"
background = "#c8cbcf"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c7785"
background = "#c8cbcf"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#71CAE4"
green = "#A0A2A7"
yellow = "#E0B0A5"
blue = "#F1CFA7"
magenta = "#BABAC3"
cyan = "#A2CFE5"
white = "#c8cbcf"

[colors.bright]
black = "#6c7785"
red = "#71CAE4"
green = "#A0A2A7"
yellow = "#E0B0A5"
blue = "#F1CFA7"
magenta = "#BABAC3"
cyan = "#A2CFE5"
white = "#c8cbcf"

[colors.dim]
black = "#c8cbcf"
red = "#71CAE4"
green = "#BABAC3"
yellow = "#E0B0A5"
blue = "#F1CFA7"
magenta = "#A0A2A7"
cyan = "#A2CFE5"
white = "#6c7785"

