[colors]
background = '#0000008e'
black = '#000000'
blue = '#D96829'
cursor = '#c6c3c2'
cyan = '#AB7251'
foreground = '#c6c3c2'
green = '#DB9B58'
magenta = '#EBB65B'
red = '#987F80'
tabs = '#c6c3c2'
tabs-active = '#C7A99F'
white = '#c6c3c2'
yellow = '#c6c3c2'
dim-black = '#0000008e'
dim-blue = '#D968298e'
dim-cyan = '#AB72518e'
dim-foreground = '#c6c3c28e'
dim-green = '#DB9B588e'
dim-magenta = '#EBB65B8e'
dim-red = '#987F808e'
dim-white = '#C7A99F8e'
dim-yellow = '#c6c3c28e'
light-black = '#D96829'
light-blue = '#AB7251'
light-cyan = '#DB9B58'
light-foreground = '#EBB65B'
light-green = '#987F80'
light-magenta = '#C7A99F'
light-red = '#c6c3c2'
light-white = '#D96829'
light-yellow = '#AB7251'
