# Shell variables
# Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/2159878-1920x1080-desktop-1080p-inazuma-eleven-background-image.jpg"

# Special
background='#000000'
foreground='#c3c4c4'
cursor='#c3c4c4'

# Colors
color0='#000000'
color1='#0C6492'
color2='#0274AD'
color3='#627887'
color4='#977C85'
color5='#4C9CB5'
color6='#9A9E9E'
color7='#c3c4c4'
color8='#5a6f6f'
color9='#0C6492'
color10='#0274AD'
color11='#627887'
color12='#977C85'
color13='#4C9CB5'
color14='#9A9E9E'
color15='#c3c4c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
