[colors]
background = '#0000008e'
black = '#000000'
blue = '#B38478'
cursor = '#c4c3c4'
cyan = '#DE9574'
foreground = '#c4c3c4'
green = '#FDC578'
magenta = '#997F81'
red = '#B79489'
tabs = '#c4c3c4'
tabs-active = '#DFAB90'
white = '#c4c3c4'
yellow = '#c4c3c4'
dim-black = '#0000008e'
dim-blue = '#B384788e'
dim-cyan = '#DE95748e'
dim-foreground = '#c4c3c48e'
dim-green = '#FDC5788e'
dim-magenta = '#997F818e'
dim-red = '#B794898e'
dim-white = '#DFAB908e'
dim-yellow = '#c4c3c48e'
light-black = '#B38478'
light-blue = '#DE9574'
light-cyan = '#FDC578'
light-foreground = '#997F81'
light-green = '#B79489'
light-magenta = '#DFAB90'
light-red = '#c4c3c4'
light-white = '#B38478'
light-yellow = '#DE9574'
