[colors]
background = '#0000008e'
black = '#000000'
blue = '#BB4446'
cursor = '#c3c1c1'
cyan = '#EC665B'
foreground = '#c3c1c1'
green = '#AB8975'
magenta = '#F9946D'
red = '#F75B8F'
tabs = '#c3c1c1'
tabs-active = '#F4A897'
white = '#c3c1c1'
yellow = '#c3c1c1'
dim-black = '#0000008e'
dim-blue = '#BB44468e'
dim-cyan = '#EC665B8e'
dim-foreground = '#c3c1c18e'
dim-green = '#AB89758e'
dim-magenta = '#F9946D8e'
dim-red = '#F75B8F8e'
dim-white = '#F4A8978e'
dim-yellow = '#c3c1c18e'
light-black = '#BB4446'
light-blue = '#EC665B'
light-cyan = '#AB8975'
light-foreground = '#F9946D'
light-green = '#F75B8F'
light-magenta = '#F4A897'
light-red = '#c3c1c1'
light-white = '#BB4446'
light-yellow = '#EC665B'
