[colors]
background = '#0000008e'
black = '#000000'
blue = '#6C5234'
cursor = '#c5c3c1'
cyan = '#3D4041'
foreground = '#c5c3c1'
green = '#504D4A'
magenta = '#6A6056'
red = '#986833'
tabs = '#c5c3c1'
tabs-active = '#8C7454'
white = '#c5c3c1'
yellow = '#c5c3c1'
dim-black = '#0000008e'
dim-blue = '#6C52348e'
dim-cyan = '#3D40418e'
dim-foreground = '#c5c3c18e'
dim-green = '#504D4A8e'
dim-magenta = '#6A60568e'
dim-red = '#9868338e'
dim-white = '#8C74548e'
dim-yellow = '#c5c3c18e'
light-black = '#6C5234'
light-blue = '#3D4041'
light-cyan = '#504D4A'
light-foreground = '#6A6056'
light-green = '#986833'
light-magenta = '#8C7454'
light-red = '#c5c3c1'
light-white = '#6C5234'
light-yellow = '#3D4041'
