[colors]
background = '#0000008e'
black = '#000000'
blue = '#5B4C70'
cursor = '#c4c2c7'
cyan = '#603889'
foreground = '#c4c2c7'
green = '#334DAD'
magenta = '#664D96'
red = '#91438E'
tabs = '#c4c2c7'
tabs-active = '#A0489A'
white = '#c4c2c7'
yellow = '#c4c2c7'
dim-black = '#0000008e'
dim-blue = '#5B4C708e'
dim-cyan = '#6038898e'
dim-foreground = '#c4c2c78e'
dim-green = '#334DAD8e'
dim-magenta = '#664D968e'
dim-red = '#91438E8e'
dim-white = '#A0489A8e'
dim-yellow = '#c4c2c78e'
light-black = '#5B4C70'
light-blue = '#603889'
light-cyan = '#334DAD'
light-foreground = '#664D96'
light-green = '#91438E'
light-magenta = '#A0489A'
light-red = '#c4c2c7'
light-white = '#5B4C70'
light-yellow = '#603889'
