[colors]
background = '#0000008e'
black = '#000000'
blue = '#F05B9A'
cursor = '#c4c3c6'
cyan = '#F730F5'
foreground = '#c4c3c6'
green = '#F461ED'
magenta = '#69A6F3'
red = '#FC9F99'
tabs = '#c4c3c6'
tabs-active = '#B4B8E0'
white = '#c4c3c6'
yellow = '#c4c3c6'
dim-black = '#0000008e'
dim-blue = '#F05B9A8e'
dim-cyan = '#F730F58e'
dim-foreground = '#c4c3c68e'
dim-green = '#F461ED8e'
dim-magenta = '#69A6F38e'
dim-red = '#FC9F998e'
dim-white = '#B4B8E08e'
dim-yellow = '#c4c3c68e'
light-black = '#F05B9A'
light-blue = '#F730F5'
light-cyan = '#F461ED'
light-foreground = '#69A6F3'
light-green = '#FC9F99'
light-magenta = '#B4B8E0'
light-red = '#c4c3c6'
light-white = '#F05B9A'
light-yellow = '#F730F5'
