[colors.primary]
background = "#000000"
foreground = "#c4c6c7"

[colors.cursor]
text = "#000000"
cursor = "#c4c6c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c6c7"

[colors.search.matches]
foreground = "#000000"
background = "#c4c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e7174"
background = "#c4c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#5E92A2"
green = "#28A4DD"
yellow = "#58ADD2"
blue = "#5CB1DE"
magenta = "#99A7A0"
cyan = "#ACC5BF"
white = "#c4c6c7"

[colors.bright]
black = "#5e7174"
red = "#5E92A2"
green = "#28A4DD"
yellow = "#58ADD2"
blue = "#5CB1DE"
magenta = "#99A7A0"
cyan = "#ACC5BF"
white = "#c4c6c7"

[colors.dim]
black = "#c4c6c7"
red = "#5E92A2"
green = "#99A7A0"
yellow = "#58ADD2"
blue = "#5CB1DE"
magenta = "#28A4DD"
cyan = "#ACC5BF"
white = "#5e7174"

