[colors.primary]
background = "#000000"
foreground = "#c6c7c2"

[colors.cursor]
text = "#000000"
cursor = "#c6c7c2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6c7c2"

[colors.search.matches]
foreground = "#000000"
background = "#c6c7c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6b715d"
background = "#c6c7c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#696053"
green = "#915C39"
yellow = "#8E6C56"
blue = "#A2926B"
magenta = "#D0AB6B"
cyan = "#5C7583"
white = "#c6c7c2"

[colors.bright]
black = "#6b715d"
red = "#696053"
green = "#915C39"
yellow = "#8E6C56"
blue = "#A2926B"
magenta = "#D0AB6B"
cyan = "#5C7583"
white = "#c6c7c2"

[colors.dim]
black = "#c6c7c2"
red = "#696053"
green = "#D0AB6B"
yellow = "#8E6C56"
blue = "#A2926B"
magenta = "#915C39"
cyan = "#5C7583"
white = "#6b715d"

