[colors]
background = '#0000008e'
black = '#000000'
blue = '#BDCA51'
cursor = '#c3c9c9'
cyan = '#F3E76C'
foreground = '#c3c9c9'
green = '#096B95'
magenta = '#1D949C'
red = '#23B0DE'
tabs = '#c3c9c9'
tabs-active = '#4DC3CF'
white = '#c3c9c9'
yellow = '#c3c9c9'
dim-black = '#0000008e'
dim-blue = '#BDCA518e'
dim-cyan = '#F3E76C8e'
dim-foreground = '#c3c9c98e'
dim-green = '#096B958e'
dim-magenta = '#1D949C8e'
dim-red = '#23B0DE8e'
dim-white = '#4DC3CF8e'
dim-yellow = '#c3c9c98e'
light-black = '#BDCA51'
light-blue = '#F3E76C'
light-cyan = '#096B95'
light-foreground = '#1D949C'
light-green = '#23B0DE'
light-magenta = '#4DC3CF'
light-red = '#c3c9c9'
light-white = '#BDCA51'
light-yellow = '#F3E76C'
