[colors.primary]
background = "#000000"
foreground = "#c2c3c6"

[colors.cursor]
text = "#000000"
cursor = "#c2c3c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c3c6"

[colors.search.matches]
foreground = "#000000"
background = "#c2c3c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a606f"
background = "#c2c3c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#646487"
green = "#8F768B"
yellow = "#837796"
blue = "#C2A5A6"
magenta = "#DCACA9"
cyan = "#ECD7CF"
white = "#c2c3c6"

[colors.bright]
black = "#5a606f"
red = "#646487"
green = "#8F768B"
yellow = "#837796"
blue = "#C2A5A6"
magenta = "#DCACA9"
cyan = "#ECD7CF"
white = "#c2c3c6"

[colors.dim]
black = "#c2c3c6"
red = "#646487"
green = "#DCACA9"
yellow = "#837796"
blue = "#C2A5A6"
magenta = "#8F768B"
cyan = "#ECD7CF"
white = "#5a606f"

