[colors]
background = '#0000008e'
black = '#000000'
blue = '#134C89'
cursor = '#c4cacc'
cyan = '#265B93'
foreground = '#c4cacc'
green = '#2B50A0'
magenta = '#5B629A'
red = '#9C7099'
tabs = '#c4cacc'
tabs-active = '#D47A9A'
white = '#c4cacc'
yellow = '#c4cacc'
dim-black = '#0000008e'
dim-blue = '#134C898e'
dim-cyan = '#265B938e'
dim-foreground = '#c4cacc8e'
dim-green = '#2B50A08e'
dim-magenta = '#5B629A8e'
dim-red = '#9C70998e'
dim-white = '#D47A9A8e'
dim-yellow = '#c4cacc8e'
light-black = '#134C89'
light-blue = '#265B93'
light-cyan = '#2B50A0'
light-foreground = '#5B629A'
light-green = '#9C7099'
light-magenta = '#D47A9A'
light-red = '#c4cacc'
light-white = '#134C89'
light-yellow = '#265B93'
