[colors.primary]
background = "#000000"
foreground = "#c4c2c7"

[colors.cursor]
text = "#000000"
cursor = "#c4c2c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c2c7"

[colors.search.matches]
foreground = "#000000"
background = "#c4c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#645e72"
background = "#c4c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#5B4C70"
green = "#603889"
yellow = "#334DAD"
blue = "#664D96"
magenta = "#91438E"
cyan = "#A0489A"
white = "#c4c2c7"

[colors.bright]
black = "#645e72"
red = "#5B4C70"
green = "#603889"
yellow = "#334DAD"
blue = "#664D96"
magenta = "#91438E"
cyan = "#A0489A"
white = "#c4c2c7"

[colors.dim]
black = "#c4c2c7"
red = "#5B4C70"
green = "#91438E"
yellow = "#334DAD"
blue = "#664D96"
magenta = "#603889"
cyan = "#A0489A"
white = "#645e72"

