[colors]
background = '#0000008e'
black = '#000000'
blue = '#225C8E'
cursor = '#c1c1c3'
cyan = '#1E61AE'
foreground = '#c1c1c3'
green = '#5B6E90'
magenta = '#54A8C6'
red = '#8E99AF'
tabs = '#c1c1c3'
tabs-active = '#9AB3CC'
white = '#c1c1c3'
yellow = '#c1c1c3'
dim-black = '#0000008e'
dim-blue = '#225C8E8e'
dim-cyan = '#1E61AE8e'
dim-foreground = '#c1c1c38e'
dim-green = '#5B6E908e'
dim-magenta = '#54A8C68e'
dim-red = '#8E99AF8e'
dim-white = '#9AB3CC8e'
dim-yellow = '#c1c1c38e'
light-black = '#225C8E'
light-blue = '#1E61AE'
light-cyan = '#5B6E90'
light-foreground = '#54A8C6'
light-green = '#8E99AF'
light-magenta = '#9AB3CC'
light-red = '#c1c1c3'
light-white = '#225C8E'
light-yellow = '#1E61AE'
