[colors.primary]
background = "#000000"
foreground = "#c3c4c4"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c4"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a6f6f"
background = "#c3c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#0C6492"
green = "#0274AD"
yellow = "#627887"
blue = "#977C85"
magenta = "#4C9CB5"
cyan = "#9A9E9E"
white = "#c3c4c4"

[colors.bright]
black = "#5a6f6f"
red = "#0C6492"
green = "#0274AD"
yellow = "#627887"
blue = "#977C85"
magenta = "#4C9CB5"
cyan = "#9A9E9E"
white = "#c3c4c4"

[colors.dim]
black = "#c3c4c4"
red = "#0C6492"
green = "#4C9CB5"
yellow = "#627887"
blue = "#977C85"
magenta = "#0274AD"
cyan = "#9A9E9E"
white = "#5a6f6f"

