[colors]
background = '#0000008e'
black = '#000000'
blue = '#B0966D'
cursor = '#c6c4c6'
cyan = '#D7996E'
foreground = '#c6c4c6'
green = '#767886'
magenta = '#A69A95'
red = '#D3B196'
tabs = '#c6c4c6'
tabs-active = '#E9D0A9'
white = '#c6c4c6'
yellow = '#c6c4c6'
dim-black = '#0000008e'
dim-blue = '#B0966D8e'
dim-cyan = '#D7996E8e'
dim-foreground = '#c6c4c68e'
dim-green = '#7678868e'
dim-magenta = '#A69A958e'
dim-red = '#D3B1968e'
dim-white = '#E9D0A98e'
dim-yellow = '#c6c4c68e'
light-black = '#B0966D'
light-blue = '#D7996E'
light-cyan = '#767886'
light-foreground = '#A69A95'
light-green = '#D3B196'
light-magenta = '#E9D0A9'
light-red = '#c6c4c6'
light-white = '#B0966D'
light-yellow = '#D7996E'
