[colors.primary]
background = "#000000"
foreground = "#c6c2c2"

[colors.cursor]
text = "#000000"
cursor = "#c6c2c2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6c2c2"

[colors.search.matches]
foreground = "#000000"
background = "#c6c2c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6f5b5b"
background = "#c6c2c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#ED6D4B"
green = "#E6B45F"
yellow = "#E5A161"
blue = "#8E7F8D"
magenta = "#A9A096"
cyan = "#DFB689"
white = "#c6c2c2"

[colors.bright]
black = "#6f5b5b"
red = "#ED6D4B"
green = "#E6B45F"
yellow = "#E5A161"
blue = "#8E7F8D"
magenta = "#A9A096"
cyan = "#DFB689"
white = "#c6c2c2"

[colors.dim]
black = "#c6c2c2"
red = "#ED6D4B"
green = "#A9A096"
yellow = "#E5A161"
blue = "#8E7F8D"
magenta = "#E6B45F"
cyan = "#DFB689"
white = "#6f5b5b"

