[colors.primary]
background = "#000000"
foreground = "#c2c1c4"

[colors.cursor]
text = "#000000"
cursor = "#c2c1c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c1c4"

[colors.search.matches]
foreground = "#000000"
background = "#c2c1c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5b596c"
background = "#c2c1c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#D23B3A"
green = "#EA5731"
yellow = "#A0354D"
blue = "#C35A55"
magenta = "#F99833"
cyan = "#FDC839"
white = "#c2c1c4"

[colors.bright]
black = "#5b596c"
red = "#D23B3A"
green = "#EA5731"
yellow = "#A0354D"
blue = "#C35A55"
magenta = "#F99833"
cyan = "#FDC839"
white = "#c2c1c4"

[colors.dim]
black = "#c2c1c4"
red = "#D23B3A"
green = "#F99833"
yellow = "#A0354D"
blue = "#C35A55"
magenta = "#EA5731"
cyan = "#FDC839"
white = "#5b596c"

