[colors]
background = '#0000008e'
black = '#000000'
blue = '#615453'
cursor = '#c2c4c6'
cyan = '#A25836'
foreground = '#c2c4c6'
green = '#9E6B4F'
magenta = '#D9A058'
red = '#D6B760'
tabs = '#c2c4c6'
tabs-active = '#7A7581'
white = '#c2c4c6'
yellow = '#c2c4c6'
dim-black = '#0000008e'
dim-blue = '#6154538e'
dim-cyan = '#A258368e'
dim-foreground = '#c2c4c68e'
dim-green = '#9E6B4F8e'
dim-magenta = '#D9A0588e'
dim-red = '#D6B7608e'
dim-white = '#7A75818e'
dim-yellow = '#c2c4c68e'
light-black = '#615453'
light-blue = '#A25836'
light-cyan = '#9E6B4F'
light-foreground = '#D9A058'
light-green = '#D6B760'
light-magenta = '#7A7581'
light-red = '#c2c4c6'
light-white = '#615453'
light-yellow = '#A25836'
