[colors.primary]
background = "#000000"
foreground = "#cbcdd0"

[colors.cursor]
text = "#000000"
cursor = "#cbcdd0"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#cbcdd0"

[colors.search.matches]
foreground = "#000000"
background = "#cbcdd0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#707e8a"
background = "#cbcdd0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#C1AAAF"
green = "#96B4CE"
yellow = "#AAD3EA"
blue = "#F7DACC"
magenta = "#FEE7D4"
cyan = "#CED6E2"
white = "#cbcdd0"

[colors.bright]
black = "#707e8a"
red = "#C1AAAF"
green = "#96B4CE"
yellow = "#AAD3EA"
blue = "#F7DACC"
magenta = "#FEE7D4"
cyan = "#CED6E2"
white = "#cbcdd0"

[colors.dim]
black = "#cbcdd0"
red = "#C1AAAF"
green = "#FEE7D4"
yellow = "#AAD3EA"
blue = "#F7DACC"
magenta = "#96B4CE"
cyan = "#CED6E2"
white = "#707e8a"

