[colors.primary]
background = "#000000"
foreground = "#c3c4c8"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c8"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c8"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f6374"
background = "#c3c4c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#296993"
green = "#2273BF"
yellow = "#596EA2"
blue = "#A277A1"
magenta = "#358AB4"
cyan = "#37A2CB"
white = "#c3c4c8"

[colors.bright]
black = "#5f6374"
red = "#296993"
green = "#2273BF"
yellow = "#596EA2"
blue = "#A277A1"
magenta = "#358AB4"
cyan = "#37A2CB"
white = "#c3c4c8"

[colors.dim]
black = "#c3c4c8"
red = "#296993"
green = "#358AB4"
yellow = "#596EA2"
blue = "#A277A1"
magenta = "#2273BF"
cyan = "#37A2CB"
white = "#5f6374"

