[colors.primary]
background = "#000000"
foreground = "#c3c4c8"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c8"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c8"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f6374"
background = "#c3c4c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#274D90"
green = "#255197"
yellow = "#3469B3"
blue = "#3A6AB6"
magenta = "#4868B3"
cyan = "#3AA0DC"
white = "#c3c4c8"

[colors.bright]
black = "#5f6374"
red = "#274D90"
green = "#255197"
yellow = "#3469B3"
blue = "#3A6AB6"
magenta = "#4868B3"
cyan = "#3AA0DC"
white = "#c3c4c8"

[colors.dim]
black = "#c3c4c8"
red = "#274D90"
green = "#4868B3"
yellow = "#3469B3"
blue = "#3A6AB6"
magenta = "#255197"
cyan = "#3AA0DC"
white = "#5f6374"

