[colors]
background = '#0000008e'
black = '#000000'
blue = '#AC9472'
cursor = '#c4c6cc'
cyan = '#225BA1'
foreground = '#c4c6cc'
green = '#2857B2'
magenta = '#5F66A0'
red = '#946D9D'
tabs = '#c4c6cc'
tabs-active = '#4B94C8'
white = '#c4c6cc'
yellow = '#c4c6cc'
dim-black = '#0000008e'
dim-blue = '#AC94728e'
dim-cyan = '#225BA18e'
dim-foreground = '#c4c6cc8e'
dim-green = '#2857B28e'
dim-magenta = '#5F66A08e'
dim-red = '#946D9D8e'
dim-white = '#4B94C88e'
dim-yellow = '#c4c6cc8e'
light-black = '#AC9472'
light-blue = '#225BA1'
light-cyan = '#2857B2'
light-foreground = '#5F66A0'
light-green = '#946D9D'
light-magenta = '#4B94C8'
light-red = '#c4c6cc'
light-white = '#AC9472'
light-yellow = '#225BA1'
