[colors.primary]
background = "#000000"
foreground = "#c1c5c5"

[colors.cursor]
text = "#000000"
cursor = "#c1c5c5"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c5c5"

[colors.search.matches]
foreground = "#000000"
background = "#c1c5c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#596d6d"
background = "#c1c5c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#31454F"
green = "#2B5366"
yellow = "#4D4F4E"
blue = "#656766"
magenta = "#A73B36"
cyan = "#80817F"
white = "#c1c5c5"

[colors.bright]
black = "#596d6d"
red = "#31454F"
green = "#2B5366"
yellow = "#4D4F4E"
blue = "#656766"
magenta = "#A73B36"
cyan = "#80817F"
white = "#c1c5c5"

[colors.dim]
black = "#c1c5c5"
red = "#31454F"
green = "#A73B36"
yellow = "#4D4F4E"
blue = "#656766"
magenta = "#2B5366"
cyan = "#80817F"
white = "#596d6d"

