[colors]
background = '#0000008e'
black = '#000000'
blue = '#9C4C6D'
cursor = '#c4c2c7'
cyan = '#B8807A'
foreground = '#c4c2c7'
green = '#59708F'
magenta = '#AA678A'
red = '#E16C90'
tabs = '#c4c2c7'
tabs-active = '#7092AC'
white = '#c4c2c7'
yellow = '#c4c2c7'
dim-black = '#0000008e'
dim-blue = '#9C4C6D8e'
dim-cyan = '#B8807A8e'
dim-foreground = '#c4c2c78e'
dim-green = '#59708F8e'
dim-magenta = '#AA678A8e'
dim-red = '#E16C908e'
dim-white = '#7092AC8e'
dim-yellow = '#c4c2c78e'
light-black = '#9C4C6D'
light-blue = '#B8807A'
light-cyan = '#59708F'
light-foreground = '#AA678A'
light-green = '#E16C90'
light-magenta = '#7092AC'
light-red = '#c4c2c7'
light-white = '#9C4C6D'
light-yellow = '#B8807A'
