[colors.primary]
background = "#000000"
foreground = "#c2c7c7"

[colors.cursor]
text = "#000000"
cursor = "#c2c7c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c7c7"

[colors.search.matches]
foreground = "#000000"
background = "#c2c7c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d7272"
background = "#c2c7c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#A56336"
green = "#5C906F"
yellow = "#C7AC58"
blue = "#3D738B"
magenta = "#6AA99A"
cyan = "#A3C3AC"
white = "#c2c7c7"

[colors.bright]
black = "#5d7272"
red = "#A56336"
green = "#5C906F"
yellow = "#C7AC58"
blue = "#3D738B"
magenta = "#6AA99A"
cyan = "#A3C3AC"
white = "#c2c7c7"

[colors.dim]
black = "#c2c7c7"
red = "#A56336"
green = "#6AA99A"
yellow = "#C7AC58"
blue = "#3D738B"
magenta = "#5C906F"
cyan = "#A3C3AC"
white = "#5d7272"

