[colors.primary]
background = "#000000"
foreground = "#c4c6cc"

[colors.cursor]
text = "#000000"
cursor = "#c4c6cc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c6cc"

[colors.search.matches]
foreground = "#000000"
background = "#c4c6cc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#65687b"
background = "#c4c6cc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#8D6A83"
green = "#768BA4"
yellow = "#9D9CB2"
blue = "#B1B5C7"
magenta = "#C2B8C7"
cyan = "#BCC7D0"
white = "#c4c6cc"

[colors.bright]
black = "#65687b"
red = "#8D6A83"
green = "#768BA4"
yellow = "#9D9CB2"
blue = "#B1B5C7"
magenta = "#C2B8C7"
cyan = "#BCC7D0"
white = "#c4c6cc"

[colors.dim]
black = "#c4c6cc"
red = "#8D6A83"
green = "#C2B8C7"
yellow = "#9D9CB2"
blue = "#B1B5C7"
magenta = "#768BA4"
cyan = "#BCC7D0"
white = "#65687b"

