[colors.primary]
background = "#000000"
foreground = "#c6c4c6"

[colors.cursor]
text = "#000000"
cursor = "#c6c4c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6c4c6"

[colors.search.matches]
foreground = "#000000"
background = "#c6c4c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6b5e74"
background = "#c6c4c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#B0966D"
green = "#D7996E"
yellow = "#767886"
blue = "#A69A95"
magenta = "#D3B196"
cyan = "#E9D0A9"
white = "#c6c4c6"

[colors.bright]
black = "#6b5e74"
red = "#B0966D"
green = "#D7996E"
yellow = "#767886"
blue = "#A69A95"
magenta = "#D3B196"
cyan = "#E9D0A9"
white = "#c6c4c6"

[colors.dim]
black = "#c6c4c6"
red = "#B0966D"
green = "#D3B196"
yellow = "#767886"
blue = "#A69A95"
magenta = "#D7996E"
cyan = "#E9D0A9"
white = "#6b5e74"

