[colors]
background = '#0000008e'
black = '#000000'
blue = '#5E92A2'
cursor = '#c4c6c7'
cyan = '#28A4DD'
foreground = '#c4c6c7'
green = '#58ADD2'
magenta = '#5CB1DE'
red = '#99A7A0'
tabs = '#c4c6c7'
tabs-active = '#ACC5BF'
white = '#c4c6c7'
yellow = '#c4c6c7'
dim-black = '#0000008e'
dim-blue = '#5E92A28e'
dim-cyan = '#28A4DD8e'
dim-foreground = '#c4c6c78e'
dim-green = '#58ADD28e'
dim-magenta = '#5CB1DE8e'
dim-red = '#99A7A08e'
dim-white = '#ACC5BF8e'
dim-yellow = '#c4c6c78e'
light-black = '#5E92A2'
light-blue = '#28A4DD'
light-cyan = '#58ADD2'
light-foreground = '#5CB1DE'
light-green = '#99A7A0'
light-magenta = '#ACC5BF'
light-red = '#c4c6c7'
light-white = '#5E92A2'
light-yellow = '#28A4DD'
