[colors]
background = '#0000008e'
black = '#000000'
blue = '#863D6F'
cursor = '#c4c4ca'
cyan = '#9B4878'
foreground = '#c4c4ca'
green = '#AF5887'
magenta = '#A17E82'
red = '#D26491'
tabs = '#c4c4ca'
tabs-active = '#F29DB0'
white = '#c4c4ca'
yellow = '#c4c4ca'
dim-black = '#0000008e'
dim-blue = '#863D6F8e'
dim-cyan = '#9B48788e'
dim-foreground = '#c4c4ca8e'
dim-green = '#AF58878e'
dim-magenta = '#A17E828e'
dim-red = '#D264918e'
dim-white = '#F29DB08e'
dim-yellow = '#c4c4ca8e'
light-black = '#863D6F'
light-blue = '#9B4878'
light-cyan = '#AF5887'
light-foreground = '#A17E82'
light-green = '#D26491'
light-magenta = '#F29DB0'
light-red = '#c4c4ca'
light-white = '#863D6F'
light-yellow = '#9B4878'
