[colors]
background = '#0000008e'
black = '#000000'
blue = '#6AC5AD'
cursor = '#c5c7c7'
cyan = '#95A8A4'
foreground = '#c5c7c7'
green = '#9ED4A3'
magenta = '#D6D89D'
red = '#94B7CF'
tabs = '#c5c7c7'
tabs-active = '#95CDCD'
white = '#c5c7c7'
yellow = '#c5c7c7'
dim-black = '#0000008e'
dim-blue = '#6AC5AD8e'
dim-cyan = '#95A8A48e'
dim-foreground = '#c5c7c78e'
dim-green = '#9ED4A38e'
dim-magenta = '#D6D89D8e'
dim-red = '#94B7CF8e'
dim-white = '#95CDCD8e'
dim-yellow = '#c5c7c78e'
light-black = '#6AC5AD'
light-blue = '#95A8A4'
light-cyan = '#9ED4A3'
light-foreground = '#D6D89D'
light-green = '#94B7CF'
light-magenta = '#95CDCD'
light-red = '#c5c7c7'
light-white = '#6AC5AD'
light-yellow = '#95A8A4'
