[colors]
background = '#0000008e'
black = '#000000'
blue = '#507298'
cursor = '#c5c6c7'
cyan = '#5D7498'
foreground = '#c5c6c7'
green = '#6C7792'
magenta = '#6C889A'
red = '#6D97A4'
tabs = '#c5c6c7'
tabs-active = '#7AA8C3'
white = '#c5c6c7'
yellow = '#c5c6c7'
dim-black = '#0000008e'
dim-blue = '#5072988e'
dim-cyan = '#5D74988e'
dim-foreground = '#c5c6c78e'
dim-green = '#6C77928e'
dim-magenta = '#6C889A8e'
dim-red = '#6D97A48e'
dim-white = '#7AA8C38e'
dim-yellow = '#c5c6c78e'
light-black = '#507298'
light-blue = '#5D7498'
light-cyan = '#6C7792'
light-foreground = '#6C889A'
light-green = '#6D97A4'
light-magenta = '#7AA8C3'
light-red = '#c5c6c7'
light-white = '#507298'
light-yellow = '#5D7498'
