[colors.primary]
background = "#000000"
foreground = "#c1c3c4"

[colors.cursor]
text = "#000000"
cursor = "#c1c3c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c3c4"

[colors.search.matches]
foreground = "#000000"
background = "#c1c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59626c"
background = "#c1c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#C4AB3F"
green = "#E0DB0E"
yellow = "#EFE709"
blue = "#95834A"
magenta = "#F59659"
cyan = "#1D728A"
white = "#c1c3c4"

[colors.bright]
black = "#59626c"
red = "#C4AB3F"
green = "#E0DB0E"
yellow = "#EFE709"
blue = "#95834A"
magenta = "#F59659"
cyan = "#1D728A"
white = "#c1c3c4"

[colors.dim]
black = "#c1c3c4"
red = "#C4AB3F"
green = "#F59659"
yellow = "#EFE709"
blue = "#95834A"
magenta = "#E0DB0E"
cyan = "#1D728A"
white = "#59626c"

