[colors]
background = '#0000008e'
black = '#000000'
blue = '#AD916F'
cursor = '#c3c5c6'
cyan = '#517987'
foreground = '#c3c5c6'
green = '#8B7E81'
magenta = '#5A8C91'
red = '#A49E97'
tabs = '#c3c5c6'
tabs-active = '#DDAD93'
white = '#c3c5c6'
yellow = '#c3c5c6'
dim-black = '#0000008e'
dim-blue = '#AD916F8e'
dim-cyan = '#5179878e'
dim-foreground = '#c3c5c68e'
dim-green = '#8B7E818e'
dim-magenta = '#5A8C918e'
dim-red = '#A49E978e'
dim-white = '#DDAD938e'
dim-yellow = '#c3c5c68e'
light-black = '#AD916F'
light-blue = '#517987'
light-cyan = '#8B7E81'
light-foreground = '#5A8C91'
light-green = '#A49E97'
light-magenta = '#DDAD93'
light-red = '#c3c5c6'
light-white = '#AD916F'
light-yellow = '#517987'
