[colors]
background = '#0000008e'
black = '#000000'
blue = '#31454F'
cursor = '#c1c5c5'
cyan = '#2B5366'
foreground = '#c1c5c5'
green = '#4D4F4E'
magenta = '#656766'
red = '#A73B36'
tabs = '#c1c5c5'
tabs-active = '#80817F'
white = '#c1c5c5'
yellow = '#c1c5c5'
dim-black = '#0000008e'
dim-blue = '#31454F8e'
dim-cyan = '#2B53668e'
dim-foreground = '#c1c5c58e'
dim-green = '#4D4F4E8e'
dim-magenta = '#6567668e'
dim-red = '#A73B368e'
dim-white = '#80817F8e'
dim-yellow = '#c1c5c58e'
light-black = '#31454F'
light-blue = '#2B5366'
light-cyan = '#4D4F4E'
light-foreground = '#656766'
light-green = '#A73B36'
light-magenta = '#80817F'
light-red = '#c1c5c5'
light-white = '#31454F'
light-yellow = '#2B5366'
