[colors]
background = '#0000008e'
black = '#000000'
blue = '#68CAFC'
cursor = '#c7cbcc'
cyan = '#B3ADA8'
foreground = '#c7cbcc'
green = '#F3A0A5'
magenta = '#E7D2A6'
red = '#A1DBF9'
tabs = '#c7cbcc'
tabs-active = '#EFDCD6'
white = '#c7cbcc'
yellow = '#c7cbcc'
dim-black = '#0000008e'
dim-blue = '#68CAFC8e'
dim-cyan = '#B3ADA88e'
dim-foreground = '#c7cbcc8e'
dim-green = '#F3A0A58e'
dim-magenta = '#E7D2A68e'
dim-red = '#A1DBF98e'
dim-white = '#EFDCD68e'
dim-yellow = '#c7cbcc8e'
light-black = '#68CAFC'
light-blue = '#B3ADA8'
light-cyan = '#F3A0A5'
light-foreground = '#E7D2A6'
light-green = '#A1DBF9'
light-magenta = '#EFDCD6'
light-red = '#c7cbcc'
light-white = '#68CAFC'
light-yellow = '#B3ADA8'
