[colors]
background = '#0000008e'
black = '#000000'
blue = '#D23B3A'
cursor = '#c2c1c4'
cyan = '#EA5731'
foreground = '#c2c1c4'
green = '#A0354D'
magenta = '#C35A55'
red = '#F99833'
tabs = '#c2c1c4'
tabs-active = '#FDC839'
white = '#c2c1c4'
yellow = '#c2c1c4'
dim-black = '#0000008e'
dim-blue = '#D23B3A8e'
dim-cyan = '#EA57318e'
dim-foreground = '#c2c1c48e'
dim-green = '#A0354D8e'
dim-magenta = '#C35A558e'
dim-red = '#F998338e'
dim-white = '#FDC8398e'
dim-yellow = '#c2c1c48e'
light-black = '#D23B3A'
light-blue = '#EA5731'
light-cyan = '#A0354D'
light-foreground = '#C35A55'
light-green = '#F99833'
light-magenta = '#FDC839'
light-red = '#c2c1c4'
light-white = '#D23B3A'
light-yellow = '#EA5731'
