[colors.primary]
background = "#000000"
foreground = "#c3c4c7"

[colors.cursor]
text = "#000000"
cursor = "#c3c4c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c4c7"

[colors.search.matches]
foreground = "#000000"
background = "#c3c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d6372"
background = "#c3c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#2F6F91"
green = "#51778F"
yellow = "#5B92AA"
blue = "#4EAAC9"
magenta = "#5DB0CE"
cyan = "#BFC9AE"
white = "#c3c4c7"

[colors.bright]
black = "#5d6372"
red = "#2F6F91"
green = "#51778F"
yellow = "#5B92AA"
blue = "#4EAAC9"
magenta = "#5DB0CE"
cyan = "#BFC9AE"
white = "#c3c4c7"

[colors.dim]
black = "#c3c4c7"
red = "#2F6F91"
green = "#5DB0CE"
yellow = "#5B92AA"
blue = "#4EAAC9"
magenta = "#51778F"
cyan = "#BFC9AE"
white = "#5d6372"

