[colors]
background = '#0000008e'
black = '#000000'
blue = '#93A0AF'
cursor = '#c8cacc'
cyan = '#CCBBBF'
foreground = '#c8cacc'
green = '#9EB7C3'
magenta = '#A8BCC6'
red = '#EEB9CC'
tabs = '#c8cacc'
tabs-active = '#CAD3DD'
white = '#c8cacc'
yellow = '#c8cacc'
dim-black = '#0000008e'
dim-blue = '#93A0AF8e'
dim-cyan = '#CCBBBF8e'
dim-foreground = '#c8cacc8e'
dim-green = '#9EB7C38e'
dim-magenta = '#A8BCC68e'
dim-red = '#EEB9CC8e'
dim-white = '#CAD3DD8e'
dim-yellow = '#c8cacc8e'
light-black = '#93A0AF'
light-blue = '#CCBBBF'
light-cyan = '#9EB7C3'
light-foreground = '#A8BCC6'
light-green = '#EEB9CC'
light-magenta = '#CAD3DD'
light-red = '#c8cacc'
light-white = '#93A0AF'
light-yellow = '#CCBBBF'
