[colors.primary]
background = "#000000"
foreground = "#c3c2c6"

[colors.cursor]
text = "#000000"
cursor = "#c3c2c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c2c6"

[colors.search.matches]
foreground = "#000000"
background = "#c3c2c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5b70"
background = "#c3c2c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#3267DE"
green = "#5B6ADA"
yellow = "#9966C1"
blue = "#418AEF"
magenta = "#6192F4"
cyan = "#9A9CF7"
white = "#c3c2c6"

[colors.bright]
black = "#5f5b70"
red = "#3267DE"
green = "#5B6ADA"
yellow = "#9966C1"
blue = "#418AEF"
magenta = "#6192F4"
cyan = "#9A9CF7"
white = "#c3c2c6"

[colors.dim]
black = "#c3c2c6"
red = "#3267DE"
green = "#6192F4"
yellow = "#9966C1"
blue = "#418AEF"
magenta = "#5B6ADA"
cyan = "#9A9CF7"
white = "#5f5b70"

