# Shell variables
# Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/wallhaven-jxl56w_1920x1080.png"

# Special
background='#000000'
foreground='#c5c7c7'
cursor='#c5c7c7'

# Colors
color0='#000000'
color1='#6AC5AD'
color2='#95A8A4'
color3='#9ED4A3'
color4='#D6D89D'
color5='#94B7CF'
color6='#95CDCD'
color7='#c5c7c7'
color8='#607572'
color9='#6AC5AD'
color10='#95A8A4'
color11='#9ED4A3'
color12='#D6D89D'
color13='#94B7CF'
color14='#95CDCD'
color15='#c5c7c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
