[colors.primary]
background = "#000000"
foreground = "#c4cacc"

[colors.cursor]
text = "#000000"
cursor = "#c4cacc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4cacc"

[colors.search.matches]
foreground = "#000000"
background = "#c4cacc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#65777c"
background = "#c4cacc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#134C89"
green = "#265B93"
yellow = "#2B50A0"
blue = "#5B629A"
magenta = "#9C7099"
cyan = "#D47A9A"
white = "#c4cacc"

[colors.bright]
black = "#65777c"
red = "#134C89"
green = "#265B93"
yellow = "#2B50A0"
blue = "#5B629A"
magenta = "#9C7099"
cyan = "#D47A9A"
white = "#c4cacc"

[colors.dim]
black = "#c4cacc"
red = "#134C89"
green = "#9C7099"
yellow = "#2B50A0"
blue = "#5B629A"
magenta = "#265B93"
cyan = "#D47A9A"
white = "#65777c"

