[colors]
background = '#0000008e'
black = '#000000'
blue = '#667BC3'
cursor = '#c3c4c9'
cyan = '#9470A7'
foreground = '#c3c4c9'
green = '#7A83B5'
magenta = '#7388D1'
red = '#7E92E1'
tabs = '#c3c4c9'
tabs-active = '#D1A0BB'
white = '#c3c4c9'
yellow = '#c3c4c9'
dim-black = '#0000008e'
dim-blue = '#667BC38e'
dim-cyan = '#9470A78e'
dim-foreground = '#c3c4c98e'
dim-green = '#7A83B58e'
dim-magenta = '#7388D18e'
dim-red = '#7E92E18e'
dim-white = '#D1A0BB8e'
dim-yellow = '#c3c4c98e'
light-black = '#667BC3'
light-blue = '#9470A7'
light-cyan = '#7A83B5'
light-foreground = '#7388D1'
light-green = '#7E92E1'
light-magenta = '#D1A0BB'
light-red = '#c3c4c9'
light-white = '#667BC3'
light-yellow = '#9470A7'
