[colors.primary]
background = "#000000"
foreground = "#c4c1c1"

[colors.cursor]
text = "#000000"
cursor = "#c4c1c1"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c1c1"

[colors.search.matches]
foreground = "#000000"
background = "#c4c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c5858"
background = "#c4c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#C54730"
green = "#EC592C"
yellow = "#F09562"
blue = "#5F7C83"
magenta = "#6D8D91"
cyan = "#F6B08D"
white = "#c4c1c1"

[colors.bright]
black = "#6c5858"
red = "#C54730"
green = "#EC592C"
yellow = "#F09562"
blue = "#5F7C83"
magenta = "#6D8D91"
cyan = "#F6B08D"
white = "#c4c1c1"

[colors.dim]
black = "#c4c1c1"
red = "#C54730"
green = "#6D8D91"
yellow = "#F09562"
blue = "#5F7C83"
magenta = "#EC592C"
cyan = "#F6B08D"
white = "#6c5858"

