[colors.primary]
background = "#000000"
foreground = "#c5c5ca"

[colors.cursor]
text = "#000000"
cursor = "#c5c5ca"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c5c5ca"

[colors.search.matches]
foreground = "#000000"
background = "#c5c5ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#656379"
background = "#c5c5ca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#5D92C3"
green = "#AE86A7"
yellow = "#E0929D"
blue = "#FDD5AC"
magenta = "#A4B9D5"
cyan = "#DAD8DC"
white = "#c5c5ca"

[colors.bright]
black = "#656379"
red = "#5D92C3"
green = "#AE86A7"
yellow = "#E0929D"
blue = "#FDD5AC"
magenta = "#A4B9D5"
cyan = "#DAD8DC"
white = "#c5c5ca"

[colors.dim]
black = "#c5c5ca"
red = "#5D92C3"
green = "#A4B9D5"
yellow = "#E0929D"
blue = "#FDD5AC"
magenta = "#AE86A7"
cyan = "#DAD8DC"
white = "#656379"

