[colors.primary]
background = "#000000"
foreground = "#c5c3c1"

[colors.cursor]
text = "#000000"
cursor = "#c5c3c1"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c5c3c1"

[colors.search.matches]
foreground = "#000000"
background = "#c5c3c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6d6259"
background = "#c5c3c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#6C5234"
green = "#3D4041"
yellow = "#504D4A"
blue = "#6A6056"
magenta = "#986833"
cyan = "#8C7454"
white = "#c5c3c1"

[colors.bright]
black = "#6d6259"
red = "#6C5234"
green = "#3D4041"
yellow = "#504D4A"
blue = "#6A6056"
magenta = "#986833"
cyan = "#8C7454"
white = "#c5c3c1"

[colors.dim]
black = "#c5c3c1"
red = "#6C5234"
green = "#986833"
yellow = "#504D4A"
blue = "#6A6056"
magenta = "#3D4041"
cyan = "#8C7454"
white = "#6d6259"

