[colors.primary]
background = "#000000"
foreground = "#c4c5cc"

[colors.cursor]
text = "#000000"
cursor = "#c4c5cc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c5cc"

[colors.search.matches]
foreground = "#000000"
background = "#c4c5cc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#65667b"
background = "#c4c5cc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#BFAA3B"
green = "#DFA923"
yellow = "#2451AF"
blue = "#57689B"
magenta = "#5E9FD5"
cyan = "#44ADCA"
white = "#c4c5cc"

[colors.bright]
black = "#65667b"
red = "#BFAA3B"
green = "#DFA923"
yellow = "#2451AF"
blue = "#57689B"
magenta = "#5E9FD5"
cyan = "#44ADCA"
white = "#c4c5cc"

[colors.dim]
black = "#c4c5cc"
red = "#BFAA3B"
green = "#5E9FD5"
yellow = "#2451AF"
blue = "#57689B"
magenta = "#DFA923"
cyan = "#44ADCA"
white = "#65667b"

