[colors]
background = '#0000008e'
black = '#000000'
blue = '#344871'
cursor = '#c2c3c5'
cyan = '#4F516E'
foreground = '#c2c3c5'
green = '#37518C'
magenta = '#4B55A0'
red = '#5468A0'
tabs = '#c2c3c5'
tabs-active = '#906983'
white = '#c2c3c5'
yellow = '#c2c3c5'
dim-black = '#0000008e'
dim-blue = '#3448718e'
dim-cyan = '#4F516E8e'
dim-foreground = '#c2c3c58e'
dim-green = '#37518C8e'
dim-magenta = '#4B55A08e'
dim-red = '#5468A08e'
dim-white = '#9069838e'
dim-yellow = '#c2c3c58e'
light-black = '#344871'
light-blue = '#4F516E'
light-cyan = '#37518C'
light-foreground = '#4B55A0'
light-green = '#5468A0'
light-magenta = '#906983'
light-red = '#c2c3c5'
light-white = '#344871'
light-yellow = '#4F516E'
