[colors]
background = '#0000008e'
black = '#000000'
blue = '#3267DE'
cursor = '#c3c2c6'
cyan = '#5B6ADA'
foreground = '#c3c2c6'
green = '#9966C1'
magenta = '#418AEF'
red = '#6192F4'
tabs = '#c3c2c6'
tabs-active = '#9A9CF7'
white = '#c3c2c6'
yellow = '#c3c2c6'
dim-black = '#0000008e'
dim-blue = '#3267DE8e'
dim-cyan = '#5B6ADA8e'
dim-foreground = '#c3c2c68e'
dim-green = '#9966C18e'
dim-magenta = '#418AEF8e'
dim-red = '#6192F48e'
dim-white = '#9A9CF78e'
dim-yellow = '#c3c2c68e'
light-black = '#3267DE'
light-blue = '#5B6ADA'
light-cyan = '#9966C1'
light-foreground = '#418AEF'
light-green = '#6192F4'
light-magenta = '#9A9CF7'
light-red = '#c3c2c6'
light-white = '#3267DE'
light-yellow = '#5B6ADA'
