foreground         #c4c4ca
background         #000000
background_opacity 1.0
cursor             #c4c4ca

active_tab_foreground     #000000
active_tab_background     #c4c4ca
inactive_tab_foreground   #c4c4ca
inactive_tab_background   #000000

active_border_color   #c4c4ca
inactive_border_color #000000
bell_border_color     #863D6F

color0       #000000
color8       #646379
color1       #863D6F
color9       #863D6F
color2       #9B4878
color10      #9B4878
color3       #AF5887
color11      #AF5887
color4       #A17E82
color12      #A17E82
color5       #D26491
color13      #D26491
color6       #F29DB0
color14      #F29DB0
color7       #c4c4ca
color15      #c4c4ca
