--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/hzd.jpg"

-- Special
background="#000000"
foreground="#c2c7c4"
cursor="#c2c7c4"

-- Colors
color0="#000000"
color1="#9EB85C"
color2="#57748E"
color3="#6F8D9F"
color4="#35B7FC"
color5="#5BB5F6"
color6="#6DC0F6"
color7="#c2c7c4"
color8="#5c7165"
color9="#9EB85C"
color10="#57748E"
color11="#6F8D9F"
color12="#35B7FC"
color13="#5BB5F6"
color14="#6DC0F6"
color15="#c2c7c4"
