[colors.primary]
background = "#000000"
foreground = "#c4c3c4"

[colors.cursor]
text = "#000000"
cursor = "#c4c3c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c3c4"

[colors.search.matches]
foreground = "#000000"
background = "#c4c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6e5a6e"
background = "#c4c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#B38478"
green = "#DE9574"
yellow = "#FDC578"
blue = "#997F81"
magenta = "#B79489"
cyan = "#DFAB90"
white = "#c4c3c4"

[colors.bright]
black = "#6e5a6e"
red = "#B38478"
green = "#DE9574"
yellow = "#FDC578"
blue = "#997F81"
magenta = "#B79489"
cyan = "#DFAB90"
white = "#c4c3c4"

[colors.dim]
black = "#c4c3c4"
red = "#B38478"
green = "#B79489"
yellow = "#FDC578"
blue = "#997F81"
magenta = "#DE9574"
cyan = "#DFAB90"
white = "#6e5a6e"

