[colors]
background = '#0000008e'
black = '#000000'
blue = '#566463'
cursor = '#c2c4c7'
cyan = '#7D8A7F'
foreground = '#c2c4c7'
green = '#4D6688'
magenta = '#A3AA9B'
red = '#BABFB3'
tabs = '#c2c4c7'
tabs-active = '#D0CDB5'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0000008e'
dim-blue = '#5664638e'
dim-cyan = '#7D8A7F8e'
dim-foreground = '#c2c4c78e'
dim-green = '#4D66888e'
dim-magenta = '#A3AA9B8e'
dim-red = '#BABFB38e'
dim-white = '#D0CDB58e'
dim-yellow = '#c2c4c78e'
light-black = '#566463'
light-blue = '#7D8A7F'
light-cyan = '#4D6688'
light-foreground = '#A3AA9B'
light-green = '#BABFB3'
light-magenta = '#D0CDB5'
light-red = '#c2c4c7'
light-white = '#566463'
light-yellow = '#7D8A7F'
