[colors]
background = '#0000008e'
black = '#000000'
blue = '#8D6A83'
cursor = '#c4c6cc'
cyan = '#768BA4'
foreground = '#c4c6cc'
green = '#9D9CB2'
magenta = '#B1B5C7'
red = '#C2B8C7'
tabs = '#c4c6cc'
tabs-active = '#BCC7D0'
white = '#c4c6cc'
yellow = '#c4c6cc'
dim-black = '#0000008e'
dim-blue = '#8D6A838e'
dim-cyan = '#768BA48e'
dim-foreground = '#c4c6cc8e'
dim-green = '#9D9CB28e'
dim-magenta = '#B1B5C78e'
dim-red = '#C2B8C78e'
dim-white = '#BCC7D08e'
dim-yellow = '#c4c6cc8e'
light-black = '#8D6A83'
light-blue = '#768BA4'
light-cyan = '#9D9CB2'
light-foreground = '#B1B5C7'
light-green = '#C2B8C7'
light-magenta = '#BCC7D0'
light-red = '#c4c6cc'
light-white = '#8D6A83'
light-yellow = '#768BA4'
