[colors.primary]
background = "#000000"
foreground = "#c7c3c2"

[colors.cursor]
text = "#000000"
cursor = "#c7c3c2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c7c3c2"

[colors.search.matches]
foreground = "#000000"
background = "#c7c3c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#71615c"
background = "#c7c3c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#8F725A"
green = "#7C8476"
yellow = "#A1886E"
blue = "#CDA272"
magenta = "#A0A49A"
cyan = "#D0BA98"
white = "#c7c3c2"

[colors.bright]
black = "#71615c"
red = "#8F725A"
green = "#7C8476"
yellow = "#A1886E"
blue = "#CDA272"
magenta = "#A0A49A"
cyan = "#D0BA98"
white = "#c7c3c2"

[colors.dim]
black = "#c7c3c2"
red = "#8F725A"
green = "#A0A49A"
yellow = "#A1886E"
blue = "#CDA272"
magenta = "#7C8476"
cyan = "#D0BA98"
white = "#71615c"

