[colors.primary]
background = "#000000"
foreground = "#c8cacc"

[colors.cursor]
text = "#000000"
cursor = "#c8cacc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c8cacc"

[colors.search.matches]
foreground = "#000000"
background = "#c8cacc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a7382"
background = "#c8cacc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#93A0AF"
green = "#CCBBBF"
yellow = "#9EB7C3"
blue = "#A8BCC6"
magenta = "#EEB9CC"
cyan = "#CAD3DD"
white = "#c8cacc"

[colors.bright]
black = "#6a7382"
red = "#93A0AF"
green = "#CCBBBF"
yellow = "#9EB7C3"
blue = "#A8BCC6"
magenta = "#EEB9CC"
cyan = "#CAD3DD"
white = "#c8cacc"

[colors.dim]
black = "#c8cacc"
red = "#93A0AF"
green = "#EEB9CC"
yellow = "#9EB7C3"
blue = "#A8BCC6"
magenta = "#CCBBBF"
cyan = "#CAD3DD"
white = "#6a7382"

