[colors]
background = '#0000008e'
black = '#000000'
blue = '#C54730'
cursor = '#c4c1c1'
cyan = '#EC592C'
foreground = '#c4c1c1'
green = '#F09562'
magenta = '#5F7C83'
red = '#6D8D91'
tabs = '#c4c1c1'
tabs-active = '#F6B08D'
white = '#c4c1c1'
yellow = '#c4c1c1'
dim-black = '#0000008e'
dim-blue = '#C547308e'
dim-cyan = '#EC592C8e'
dim-foreground = '#c4c1c18e'
dim-green = '#F095628e'
dim-magenta = '#5F7C838e'
dim-red = '#6D8D918e'
dim-white = '#F6B08D8e'
dim-yellow = '#c4c1c18e'
light-black = '#C54730'
light-blue = '#EC592C'
light-cyan = '#F09562'
light-foreground = '#5F7C83'
light-green = '#6D8D91'
light-magenta = '#F6B08D'
light-red = '#c4c1c1'
light-white = '#C54730'
light-yellow = '#EC592C'
