[colors]
background = '#0000008e'
black = '#000000'
blue = '#326698'
cursor = '#c2c3c7'
cyan = '#5D748C'
foreground = '#c2c3c7'
green = '#6E899A'
magenta = '#4694A9'
red = '#96A0AA'
tabs = '#c2c3c7'
tabs-active = '#C8BEBA'
white = '#c2c3c7'
yellow = '#c2c3c7'
dim-black = '#0000008e'
dim-blue = '#3266988e'
dim-cyan = '#5D748C8e'
dim-foreground = '#c2c3c78e'
dim-green = '#6E899A8e'
dim-magenta = '#4694A98e'
dim-red = '#96A0AA8e'
dim-white = '#C8BEBA8e'
dim-yellow = '#c2c3c78e'
light-black = '#326698'
light-blue = '#5D748C'
light-cyan = '#6E899A'
light-foreground = '#4694A9'
light-green = '#96A0AA'
light-magenta = '#C8BEBA'
light-red = '#c2c3c7'
light-white = '#326698'
light-yellow = '#5D748C'
