[colors.primary]
background = "#000000"
foreground = "#c5c6c7"

[colors.cursor]
text = "#000000"
cursor = "#c5c6c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c5c6c7"

[colors.search.matches]
foreground = "#000000"
background = "#c5c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606676"
background = "#c5c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#507298"
green = "#5D7498"
yellow = "#6C7792"
blue = "#6C889A"
magenta = "#6D97A4"
cyan = "#7AA8C3"
white = "#c5c6c7"

[colors.bright]
black = "#606676"
red = "#507298"
green = "#5D7498"
yellow = "#6C7792"
blue = "#6C889A"
magenta = "#6D97A4"
cyan = "#7AA8C3"
white = "#c5c6c7"

[colors.dim]
black = "#c5c6c7"
red = "#507298"
green = "#6D97A4"
yellow = "#6C7792"
blue = "#6C889A"
magenta = "#5D7498"
cyan = "#7AA8C3"
white = "#606676"

