[colors.primary]
background = "#000000"
foreground = "#c3c3c6"

[colors.cursor]
text = "#000000"
cursor = "#c3c3c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c3c6"

[colors.search.matches]
foreground = "#000000"
background = "#c3c3c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d5d71"
background = "#c3c3c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#39445C"
green = "#3E4A63"
yellow = "#43425E"
blue = "#4E4A77"
magenta = "#4A637D"
cyan = "#555384"
white = "#c3c3c6"

[colors.bright]
black = "#5d5d71"
red = "#39445C"
green = "#3E4A63"
yellow = "#43425E"
blue = "#4E4A77"
magenta = "#4A637D"
cyan = "#555384"
white = "#c3c3c6"

[colors.dim]
black = "#c3c3c6"
red = "#39445C"
green = "#4A637D"
yellow = "#43425E"
blue = "#4E4A77"
magenta = "#3E4A63"
cyan = "#555384"
white = "#5d5d71"

