[colors.primary]
background = "#000000"
foreground = "#c4c5ca"

[colors.cursor]
text = "#000000"
cursor = "#c4c5ca"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c5ca"

[colors.search.matches]
foreground = "#000000"
background = "#c4c5ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#636679"
background = "#c4c5ca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#556E9C"
green = "#937989"
yellow = "#F5628D"
blue = "#459FD0"
magenta = "#9D8896"
cyan = "#DCABA9"
white = "#c4c5ca"

[colors.bright]
black = "#636679"
red = "#556E9C"
green = "#937989"
yellow = "#F5628D"
blue = "#459FD0"
magenta = "#9D8896"
cyan = "#DCABA9"
white = "#c4c5ca"

[colors.dim]
black = "#c4c5ca"
red = "#556E9C"
green = "#9D8896"
yellow = "#F5628D"
blue = "#459FD0"
magenta = "#937989"
cyan = "#DCABA9"
white = "#636679"

