[colors.primary]
background = "#000000"
foreground = "#c3c5c6"

[colors.cursor]
text = "#000000"
cursor = "#c3c5c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c5c6"

[colors.search.matches]
foreground = "#000000"
background = "#c3c5c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d6a71"
background = "#c3c5c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#AD916F"
green = "#517987"
yellow = "#8B7E81"
blue = "#5A8C91"
magenta = "#A49E97"
cyan = "#DDAD93"
white = "#c3c5c6"

[colors.bright]
black = "#5d6a71"
red = "#AD916F"
green = "#517987"
yellow = "#8B7E81"
blue = "#5A8C91"
magenta = "#A49E97"
cyan = "#DDAD93"
white = "#c3c5c6"

[colors.dim]
black = "#c3c5c6"
red = "#AD916F"
green = "#A49E97"
yellow = "#8B7E81"
blue = "#5A8C91"
magenta = "#517987"
cyan = "#DDAD93"
white = "#5d6a71"

