[colors.primary]
background = "#000000"
foreground = "#c2c4c7"

[colors.cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.search.matches]
foreground = "#000000"
background = "#c2c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6571"
background = "#c2c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#485157"
green = "#58646B"
yellow = "#9E6526"
blue = "#6B9F73"
magenta = "#D3AB3E"
cyan = "#697A85"
white = "#c2c4c7"

[colors.bright]
black = "#5c6571"
red = "#485157"
green = "#58646B"
yellow = "#9E6526"
blue = "#6B9F73"
magenta = "#D3AB3E"
cyan = "#697A85"
white = "#c2c4c7"

[colors.dim]
black = "#c2c4c7"
red = "#485157"
green = "#D3AB3E"
yellow = "#9E6526"
blue = "#6B9F73"
magenta = "#58646B"
cyan = "#697A85"
white = "#5c6571"

