[colors]
background = '#0000008e'
black = '#000000'
blue = '#C6B978'
cursor = '#c4c6cb'
cyan = '#546D8B'
foreground = '#c4c6cb'
green = '#A26FBC'
magenta = '#649390'
red = '#51AAA9'
tabs = '#c4c6cb'
tabs-active = '#B4A8BC'
white = '#c4c6cb'
yellow = '#c4c6cb'
dim-black = '#0000008e'
dim-blue = '#C6B9788e'
dim-cyan = '#546D8B8e'
dim-foreground = '#c4c6cb8e'
dim-green = '#A26FBC8e'
dim-magenta = '#6493908e'
dim-red = '#51AAA98e'
dim-white = '#B4A8BC8e'
dim-yellow = '#c4c6cb8e'
light-black = '#C6B978'
light-blue = '#546D8B'
light-cyan = '#A26FBC'
light-foreground = '#649390'
light-green = '#51AAA9'
light-magenta = '#B4A8BC'
light-red = '#c4c6cb'
light-white = '#C6B978'
light-yellow = '#546D8B'
