[colors]
background = '#0000008e'
black = '#000000'
blue = '#C6C4B3'
cursor = '#c6c7c9'
cyan = '#A4B9C5'
foreground = '#c6c7c9'
green = '#B5CBCF'
magenta = '#BEE6E8'
red = '#C9D6D4'
tabs = '#c6c7c9'
tabs-active = '#CFECED'
white = '#c6c7c9'
yellow = '#c6c7c9'
dim-black = '#0000008e'
dim-blue = '#C6C4B38e'
dim-cyan = '#A4B9C58e'
dim-foreground = '#c6c7c98e'
dim-green = '#B5CBCF8e'
dim-magenta = '#BEE6E88e'
dim-red = '#C9D6D48e'
dim-white = '#CFECED8e'
dim-yellow = '#c6c7c98e'
light-black = '#C6C4B3'
light-blue = '#A4B9C5'
light-cyan = '#B5CBCF'
light-foreground = '#BEE6E8'
light-green = '#C9D6D4'
light-magenta = '#CFECED'
light-red = '#c6c7c9'
light-white = '#C6C4B3'
light-yellow = '#A4B9C5'
