[colors]
background = '#0000008e'
black = '#000000'
blue = '#573264'
cursor = '#c3c2c7'
cyan = '#684C68'
foreground = '#c3c2c7'
green = '#B55D5F'
magenta = '#975B6A'
red = '#E6986F'
tabs = '#c3c2c7'
tabs-active = '#735787'
white = '#c3c2c7'
yellow = '#c3c2c7'
dim-black = '#0000008e'
dim-blue = '#5732648e'
dim-cyan = '#684C688e'
dim-foreground = '#c3c2c78e'
dim-green = '#B55D5F8e'
dim-magenta = '#975B6A8e'
dim-red = '#E6986F8e'
dim-white = '#7357878e'
dim-yellow = '#c3c2c78e'
light-black = '#573264'
light-blue = '#684C68'
light-cyan = '#B55D5F'
light-foreground = '#975B6A'
light-green = '#E6986F'
light-magenta = '#735787'
light-red = '#c3c2c7'
light-white = '#573264'
light-yellow = '#684C68'
