[colors.primary]
background = "#000000"
foreground = "#c3c2c6"

[colors.cursor]
text = "#000000"
cursor = "#c3c2c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c2c6"

[colors.search.matches]
foreground = "#000000"
background = "#c3c2c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5c70"
background = "#c3c2c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#B7867B"
green = "#736C8B"
yellow = "#8F7596"
blue = "#A07692"
magenta = "#CA7984"
cyan = "#A3869A"
white = "#c3c2c6"

[colors.bright]
black = "#5f5c70"
red = "#B7867B"
green = "#736C8B"
yellow = "#8F7596"
blue = "#A07692"
magenta = "#CA7984"
cyan = "#A3869A"
white = "#c3c2c6"

[colors.dim]
black = "#c3c2c6"
red = "#B7867B"
green = "#CA7984"
yellow = "#8F7596"
blue = "#A07692"
magenta = "#736C8B"
cyan = "#A3869A"
white = "#5f5c70"

