[colors.primary]
background = "#000000"
foreground = "#c2c4c7"

[colors.cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.search.matches]
foreground = "#000000"
background = "#c2c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6571"
background = "#c2c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#334853"
green = "#3B5364"
yellow = "#565E5F"
blue = "#8E725B"
magenta = "#A1906C"
cyan = "#6A7C81"
white = "#c2c4c7"

[colors.bright]
black = "#5c6571"
red = "#334853"
green = "#3B5364"
yellow = "#565E5F"
blue = "#8E725B"
magenta = "#A1906C"
cyan = "#6A7C81"
white = "#c2c4c7"

[colors.dim]
black = "#c2c4c7"
red = "#334853"
green = "#A1906C"
yellow = "#565E5F"
blue = "#8E725B"
magenta = "#3B5364"
cyan = "#6A7C81"
white = "#5c6571"

