[colors]
background = '#0000008e'
black = '#000000'
blue = '#274D8E'
cursor = '#c8c6ca'
cyan = '#2962A9'
foreground = '#c8c6ca'
green = '#486098'
magenta = '#1F76D4'
red = '#90718B'
tabs = '#c8c6ca'
tabs-active = '#2599DF'
white = '#c8c6ca'
yellow = '#c8c6ca'
dim-black = '#0000008e'
dim-blue = '#274D8E8e'
dim-cyan = '#2962A98e'
dim-foreground = '#c8c6ca8e'
dim-green = '#4860988e'
dim-magenta = '#1F76D48e'
dim-red = '#90718B8e'
dim-white = '#2599DF8e'
dim-yellow = '#c8c6ca8e'
light-black = '#274D8E'
light-blue = '#2962A9'
light-cyan = '#486098'
light-foreground = '#1F76D4'
light-green = '#90718B'
light-magenta = '#2599DF'
light-red = '#c8c6ca'
light-white = '#274D8E'
light-yellow = '#2962A9'
