[colors.primary]
background = "#000000"
foreground = "#c8c9d2"

[colors.cursor]
text = "#000000"
cursor = "#c8c9d2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c8c9d2"

[colors.search.matches]
foreground = "#000000"
background = "#c8c9d2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#707389"
background = "#c8c9d2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#3C82CE"
green = "#6693CE"
yellow = "#9D93B7"
blue = "#DFAFB7"
magenta = "#9EADD1"
cyan = "#D3B4CA"
white = "#c8c9d2"

[colors.bright]
black = "#707389"
red = "#3C82CE"
green = "#6693CE"
yellow = "#9D93B7"
blue = "#DFAFB7"
magenta = "#9EADD1"
cyan = "#D3B4CA"
white = "#c8c9d2"

[colors.dim]
black = "#c8c9d2"
red = "#3C82CE"
green = "#9EADD1"
yellow = "#9D93B7"
blue = "#DFAFB7"
magenta = "#6693CE"
cyan = "#D3B4CA"
white = "#707389"

