[colors]
background = '#0000008e'
black = '#000000'
blue = '#4C4C56'
cursor = '#c3c4c7'
cyan = '#5C5D6A'
foreground = '#c3c4c7'
green = '#936F6E'
magenta = '#A6867A'
red = '#335D84'
tabs = '#c3c4c7'
tabs-active = '#556E90'
white = '#c3c4c7'
yellow = '#c3c4c7'
dim-black = '#0000008e'
dim-blue = '#4C4C568e'
dim-cyan = '#5C5D6A8e'
dim-foreground = '#c3c4c78e'
dim-green = '#936F6E8e'
dim-magenta = '#A6867A8e'
dim-red = '#335D848e'
dim-white = '#556E908e'
dim-yellow = '#c3c4c78e'
light-black = '#4C4C56'
light-blue = '#5C5D6A'
light-cyan = '#936F6E'
light-foreground = '#A6867A'
light-green = '#335D84'
light-magenta = '#556E90'
light-red = '#c3c4c7'
light-white = '#4C4C56'
light-yellow = '#5C5D6A'
