[colors]
background = '#0000008e'
black = '#000000'
blue = '#B19CC5'
cursor = '#ddd1d8'
cyan = '#92ABD8'
foreground = '#ddd1d8'
green = '#AEB0D4'
magenta = '#CB9DC2'
red = '#D0ADC8'
tabs = '#ddd1d8'
tabs-active = '#EFB3C5'
white = '#ddd1d8'
yellow = '#ddd1d8'
dim-black = '#0000008e'
dim-blue = '#B19CC58e'
dim-cyan = '#92ABD88e'
dim-foreground = '#ddd1d88e'
dim-green = '#AEB0D48e'
dim-magenta = '#CB9DC28e'
dim-red = '#D0ADC88e'
dim-white = '#EFB3C58e'
dim-yellow = '#ddd1d88e'
light-black = '#B19CC5'
light-blue = '#92ABD8'
light-cyan = '#AEB0D4'
light-foreground = '#CB9DC2'
light-green = '#D0ADC8'
light-magenta = '#EFB3C5'
light-red = '#ddd1d8'
light-white = '#B19CC5'
light-yellow = '#92ABD8'
