[colors]
background = '#0000008e'
black = '#000000'
blue = '#3C82CE'
cursor = '#c8c9d2'
cyan = '#6693CE'
foreground = '#c8c9d2'
green = '#9D93B7'
magenta = '#DFAFB7'
red = '#9EADD1'
tabs = '#c8c9d2'
tabs-active = '#D3B4CA'
white = '#c8c9d2'
yellow = '#c8c9d2'
dim-black = '#0000008e'
dim-blue = '#3C82CE8e'
dim-cyan = '#6693CE8e'
dim-foreground = '#c8c9d28e'
dim-green = '#9D93B78e'
dim-magenta = '#DFAFB78e'
dim-red = '#9EADD18e'
dim-white = '#D3B4CA8e'
dim-yellow = '#c8c9d28e'
light-black = '#3C82CE'
light-blue = '#6693CE'
light-cyan = '#9D93B7'
light-foreground = '#DFAFB7'
light-green = '#9EADD1'
light-magenta = '#D3B4CA'
light-red = '#c8c9d2'
light-white = '#3C82CE'
light-yellow = '#6693CE'
