[colors]
background = '#0000008e'
black = '#000000'
blue = '#A56336'
cursor = '#c2c7c7'
cyan = '#5C906F'
foreground = '#c2c7c7'
green = '#C7AC58'
magenta = '#3D738B'
red = '#6AA99A'
tabs = '#c2c7c7'
tabs-active = '#A3C3AC'
white = '#c2c7c7'
yellow = '#c2c7c7'
dim-black = '#0000008e'
dim-blue = '#A563368e'
dim-cyan = '#5C906F8e'
dim-foreground = '#c2c7c78e'
dim-green = '#C7AC588e'
dim-magenta = '#3D738B8e'
dim-red = '#6AA99A8e'
dim-white = '#A3C3AC8e'
dim-yellow = '#c2c7c78e'
light-black = '#A56336'
light-blue = '#5C906F'
light-cyan = '#C7AC58'
light-foreground = '#3D738B'
light-green = '#6AA99A'
light-magenta = '#A3C3AC'
light-red = '#c2c7c7'
light-white = '#A56336'
light-yellow = '#5C906F'
