[colors.primary]
background = "#000000"
foreground = "#c3c3c4"

[colors.cursor]
text = "#000000"
cursor = "#c3c3c4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c3c4"

[colors.search.matches]
foreground = "#000000"
background = "#c3c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5a6f"
background = "#c3c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#654847"
green = "#90363B"
yellow = "#913A45"
blue = "#A0514F"
magenta = "#D3685B"
cyan = "#E0956E"
white = "#c3c3c4"

[colors.bright]
black = "#5f5a6f"
red = "#654847"
green = "#90363B"
yellow = "#913A45"
blue = "#A0514F"
magenta = "#D3685B"
cyan = "#E0956E"
white = "#c3c3c4"

[colors.dim]
black = "#c3c3c4"
red = "#654847"
green = "#D3685B"
yellow = "#913A45"
blue = "#A0514F"
magenta = "#90363B"
cyan = "#E0956E"
white = "#5f5a6f"

