[colors.primary]
background = "#000000"
foreground = "#c2c4c7"

[colors.cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c4c7"

[colors.search.matches]
foreground = "#000000"
background = "#c2c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d6472"
background = "#c2c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#566463"
green = "#7D8A7F"
yellow = "#4D6688"
blue = "#A3AA9B"
magenta = "#BABFB3"
cyan = "#D0CDB5"
white = "#c2c4c7"

[colors.bright]
black = "#5d6472"
red = "#566463"
green = "#7D8A7F"
yellow = "#4D6688"
blue = "#A3AA9B"
magenta = "#BABFB3"
cyan = "#D0CDB5"
white = "#c2c4c7"

[colors.dim]
black = "#c2c4c7"
red = "#566463"
green = "#BABFB3"
yellow = "#4D6688"
blue = "#A3AA9B"
magenta = "#7D8A7F"
cyan = "#D0CDB5"
white = "#5d6472"

