[colors.primary]
background = "#000000"
foreground = "#c6cacf"

[colors.cursor]
text = "#000000"
cursor = "#c6cacf"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6cacf"

[colors.search.matches]
foreground = "#000000"
background = "#c6cacf"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a7581"
background = "#c6cacf"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#3272A9"
green = "#3894BD"
yellow = "#15A2D9"
blue = "#28CBF4"
magenta = "#5DD3F4"
cyan = "#9EA7B9"
white = "#c6cacf"

[colors.bright]
black = "#6a7581"
red = "#3272A9"
green = "#3894BD"
yellow = "#15A2D9"
blue = "#28CBF4"
magenta = "#5DD3F4"
cyan = "#9EA7B9"
white = "#c6cacf"

[colors.dim]
black = "#c6cacf"
red = "#3272A9"
green = "#5DD3F4"
yellow = "#15A2D9"
blue = "#28CBF4"
magenta = "#3894BD"
cyan = "#9EA7B9"
white = "#6a7581"

