[colors.primary]
background = "#000000"
foreground = "#c1c0c0"

[colors.cursor]
text = "#000000"
cursor = "#c1c0c0"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c0c0"

[colors.search.matches]
foreground = "#000000"
background = "#c1c0c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#665353"
background = "#c1c0c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#937290"
green = "#AF78AC"
yellow = "#90879A"
blue = "#A290A3"
magenta = "#AF96A6"
cyan = "#D4A7AF"
white = "#c1c0c0"

[colors.bright]
black = "#665353"
red = "#937290"
green = "#AF78AC"
yellow = "#90879A"
blue = "#A290A3"
magenta = "#AF96A6"
cyan = "#D4A7AF"
white = "#c1c0c0"

[colors.dim]
black = "#c1c0c0"
red = "#937290"
green = "#AF96A6"
yellow = "#90879A"
blue = "#A290A3"
magenta = "#AF78AC"
cyan = "#D4A7AF"
white = "#665353"

