[colors]
background = '#0000008e'
black = '#000000'
blue = '#2F6F91'
cursor = '#c3c4c7'
cyan = '#51778F'
foreground = '#c3c4c7'
green = '#5B92AA'
magenta = '#4EAAC9'
red = '#5DB0CE'
tabs = '#c3c4c7'
tabs-active = '#BFC9AE'
white = '#c3c4c7'
yellow = '#c3c4c7'
dim-black = '#0000008e'
dim-blue = '#2F6F918e'
dim-cyan = '#51778F8e'
dim-foreground = '#c3c4c78e'
dim-green = '#5B92AA8e'
dim-magenta = '#4EAAC98e'
dim-red = '#5DB0CE8e'
dim-white = '#BFC9AE8e'
dim-yellow = '#c3c4c78e'
light-black = '#2F6F91'
light-blue = '#51778F'
light-cyan = '#5B92AA'
light-foreground = '#4EAAC9'
light-green = '#5DB0CE'
light-magenta = '#BFC9AE'
light-red = '#c3c4c7'
light-white = '#2F6F91'
light-yellow = '#51778F'
