[colors]
background = '#0000008e'
black = '#000000'
blue = '#E05E21'
cursor = '#c6c2c2'
cyan = '#D26F24'
foreground = '#c6c2c2'
green = '#EA952A'
magenta = '#FDDD27'
red = '#F1A557'
tabs = '#c6c2c2'
tabs-active = '#FAE059'
white = '#c6c2c2'
yellow = '#c6c2c2'
dim-black = '#0000008e'
dim-blue = '#E05E218e'
dim-cyan = '#D26F248e'
dim-foreground = '#c6c2c28e'
dim-green = '#EA952A8e'
dim-magenta = '#FDDD278e'
dim-red = '#F1A5578e'
dim-white = '#FAE0598e'
dim-yellow = '#c6c2c28e'
light-black = '#E05E21'
light-blue = '#D26F24'
light-cyan = '#EA952A'
light-foreground = '#FDDD27'
light-green = '#F1A557'
light-magenta = '#FAE059'
light-red = '#c6c2c2'
light-white = '#E05E21'
light-yellow = '#D26F24'
