[colors.primary]
background = "#000000"
foreground = "#c6c7c9"

[colors.cursor]
text = "#000000"
cursor = "#c6c7c9"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6c7c9"

[colors.search.matches]
foreground = "#000000"
background = "#c6c7c9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#636e7a"
background = "#c6c7c9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#C6C4B3"
green = "#A4B9C5"
yellow = "#B5CBCF"
blue = "#BEE6E8"
magenta = "#C9D6D4"
cyan = "#CFECED"
white = "#c6c7c9"

[colors.bright]
black = "#636e7a"
red = "#C6C4B3"
green = "#A4B9C5"
yellow = "#B5CBCF"
blue = "#BEE6E8"
magenta = "#C9D6D4"
cyan = "#CFECED"
white = "#c6c7c9"

[colors.dim]
black = "#c6c7c9"
red = "#C6C4B3"
green = "#C9D6D4"
yellow = "#B5CBCF"
blue = "#BEE6E8"
magenta = "#A4B9C5"
cyan = "#CFECED"
white = "#636e7a"

