[colors]
background = '#0000008e'
black = '#000000'
blue = '#C4AB3F'
cursor = '#c1c3c4'
cyan = '#E0DB0E'
foreground = '#c1c3c4'
green = '#EFE709'
magenta = '#95834A'
red = '#F59659'
tabs = '#c1c3c4'
tabs-active = '#1D728A'
white = '#c1c3c4'
yellow = '#c1c3c4'
dim-black = '#0000008e'
dim-blue = '#C4AB3F8e'
dim-cyan = '#E0DB0E8e'
dim-foreground = '#c1c3c48e'
dim-green = '#EFE7098e'
dim-magenta = '#95834A8e'
dim-red = '#F596598e'
dim-white = '#1D728A8e'
dim-yellow = '#c1c3c48e'
light-black = '#C4AB3F'
light-blue = '#E0DB0E'
light-cyan = '#EFE709'
light-foreground = '#95834A'
light-green = '#F59659'
light-magenta = '#1D728A'
light-red = '#c1c3c4'
light-white = '#C4AB3F'
light-yellow = '#E0DB0E'
