[colors]
background = '#0000008e'
black = '#000000'
blue = '#334853'
cursor = '#c2c4c7'
cyan = '#3B5364'
foreground = '#c2c4c7'
green = '#565E5F'
magenta = '#8E725B'
red = '#A1906C'
tabs = '#c2c4c7'
tabs-active = '#6A7C81'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0000008e'
dim-blue = '#3348538e'
dim-cyan = '#3B53648e'
dim-foreground = '#c2c4c78e'
dim-green = '#565E5F8e'
dim-magenta = '#8E725B8e'
dim-red = '#A1906C8e'
dim-white = '#6A7C818e'
dim-yellow = '#c2c4c78e'
light-black = '#334853'
light-blue = '#3B5364'
light-cyan = '#565E5F'
light-foreground = '#8E725B'
light-green = '#A1906C'
light-magenta = '#6A7C81'
light-red = '#c2c4c7'
light-white = '#334853'
light-yellow = '#3B5364'
