[colors.primary]
background = "#000000"
foreground = "#c3c3c3"

[colors.cursor]
text = "#000000"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#000000"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59596d"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#D65F39"
green = "#9D6A4F"
yellow = "#C89548"
blue = "#DFA05A"
magenta = "#FADD70"
cyan = "#668EAB"
white = "#c3c3c3"

[colors.bright]
black = "#59596d"
red = "#D65F39"
green = "#9D6A4F"
yellow = "#C89548"
blue = "#DFA05A"
magenta = "#FADD70"
cyan = "#668EAB"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#D65F39"
green = "#FADD70"
yellow = "#C89548"
blue = "#DFA05A"
magenta = "#9D6A4F"
cyan = "#668EAB"
white = "#59596d"

