[colors.primary]
background = "#000000"
foreground = "#c6caca"

[colors.cursor]
text = "#000000"
cursor = "#c6caca"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6caca"

[colors.search.matches]
foreground = "#000000"
background = "#c6caca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#647a7a"
background = "#c6caca"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#4B95AE"
green = "#57A4A8"
yellow = "#9CACA2"
blue = "#E5ACA1"
magenta = "#A8C8AA"
cyan = "#DDCDB2"
white = "#c6caca"

[colors.bright]
black = "#647a7a"
red = "#4B95AE"
green = "#57A4A8"
yellow = "#9CACA2"
blue = "#E5ACA1"
magenta = "#A8C8AA"
cyan = "#DDCDB2"
white = "#c6caca"

[colors.dim]
black = "#c6caca"
red = "#4B95AE"
green = "#A8C8AA"
yellow = "#9CACA2"
blue = "#E5ACA1"
magenta = "#57A4A8"
cyan = "#DDCDB2"
white = "#647a7a"

