[colors]
background = '#0000008e'
black = '#000000'
blue = '#937290'
cursor = '#c1c0c0'
cyan = '#AF78AC'
foreground = '#c1c0c0'
green = '#90879A'
magenta = '#A290A3'
red = '#AF96A6'
tabs = '#c1c0c0'
tabs-active = '#D4A7AF'
white = '#c1c0c0'
yellow = '#c1c0c0'
dim-black = '#0000008e'
dim-blue = '#9372908e'
dim-cyan = '#AF78AC8e'
dim-foreground = '#c1c0c08e'
dim-green = '#90879A8e'
dim-magenta = '#A290A38e'
dim-red = '#AF96A68e'
dim-white = '#D4A7AF8e'
dim-yellow = '#c1c0c08e'
light-black = '#937290'
light-blue = '#AF78AC'
light-cyan = '#90879A'
light-foreground = '#A290A3'
light-green = '#AF96A6'
light-magenta = '#D4A7AF'
light-red = '#c1c0c0'
light-white = '#937290'
light-yellow = '#AF78AC'
