[colors]
background = '#0000008e'
black = '#000000'
blue = '#E27051'
cursor = '#c7c2c3'
cyan = '#F09863'
foreground = '#c7c2c3'
green = '#F6CA40'
magenta = '#AC6F87'
red = '#B29C9F'
tabs = '#c7c2c3'
tabs-active = '#EDAB92'
white = '#c7c2c3'
yellow = '#c7c2c3'
dim-black = '#0000008e'
dim-blue = '#E270518e'
dim-cyan = '#F098638e'
dim-foreground = '#c7c2c38e'
dim-green = '#F6CA408e'
dim-magenta = '#AC6F878e'
dim-red = '#B29C9F8e'
dim-white = '#EDAB928e'
dim-yellow = '#c7c2c38e'
light-black = '#E27051'
light-blue = '#F09863'
light-cyan = '#F6CA40'
light-foreground = '#AC6F87'
light-green = '#B29C9F'
light-magenta = '#EDAB92'
light-red = '#c7c2c3'
light-white = '#E27051'
light-yellow = '#F09863'
