[colors]
background = '#0000008e'
black = '#000000'
blue = '#3478CA'
cursor = '#c5c8cd'
cyan = '#437CC5'
foreground = '#c5c8cd'
green = '#917593'
magenta = '#3A88DB'
red = '#488AD5'
tabs = '#c5c8cd'
tabs-active = '#53A2E7'
white = '#c5c8cd'
yellow = '#c5c8cd'
dim-black = '#0000008e'
dim-blue = '#3478CA8e'
dim-cyan = '#437CC58e'
dim-foreground = '#c5c8cd8e'
dim-green = '#9175938e'
dim-magenta = '#3A88DB8e'
dim-red = '#488AD58e'
dim-white = '#53A2E78e'
dim-yellow = '#c5c8cd8e'
light-black = '#3478CA'
light-blue = '#437CC5'
light-cyan = '#917593'
light-foreground = '#3A88DB'
light-green = '#488AD5'
light-magenta = '#53A2E7'
light-red = '#c5c8cd'
light-white = '#3478CA'
light-yellow = '#437CC5'
