[colors.primary]
background = "#000000"
foreground = "#c5c7c7"

[colors.cursor]
text = "#000000"
cursor = "#c5c7c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c5c7c7"

[colors.search.matches]
foreground = "#000000"
background = "#c5c7c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#607572"
background = "#c5c7c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#6AC5AD"
green = "#95A8A4"
yellow = "#9ED4A3"
blue = "#D6D89D"
magenta = "#94B7CF"
cyan = "#95CDCD"
white = "#c5c7c7"

[colors.bright]
black = "#607572"
red = "#6AC5AD"
green = "#95A8A4"
yellow = "#9ED4A3"
blue = "#D6D89D"
magenta = "#94B7CF"
cyan = "#95CDCD"
white = "#c5c7c7"

[colors.dim]
black = "#c5c7c7"
red = "#6AC5AD"
green = "#94B7CF"
yellow = "#9ED4A3"
blue = "#D6D89D"
magenta = "#95A8A4"
cyan = "#95CDCD"
white = "#607572"

