[colors.primary]
background = "#000000"
foreground = "#c1c1c3"

[colors.cursor]
text = "#000000"
cursor = "#c1c1c3"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c1c3"

[colors.search.matches]
foreground = "#000000"
background = "#c1c1c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#575a6a"
background = "#c1c1c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#225C8E"
green = "#1E61AE"
yellow = "#5B6E90"
blue = "#54A8C6"
magenta = "#8E99AF"
cyan = "#9AB3CC"
white = "#c1c1c3"

[colors.bright]
black = "#575a6a"
red = "#225C8E"
green = "#1E61AE"
yellow = "#5B6E90"
blue = "#54A8C6"
magenta = "#8E99AF"
cyan = "#9AB3CC"
white = "#c1c1c3"

[colors.dim]
black = "#c1c1c3"
red = "#225C8E"
green = "#8E99AF"
yellow = "#5B6E90"
blue = "#54A8C6"
magenta = "#1E61AE"
cyan = "#9AB3CC"
white = "#575a6a"

