[colors]
background = '#0000008e'
black = '#000000'
blue = '#654847'
cursor = '#c3c3c4'
cyan = '#90363B'
foreground = '#c3c3c4'
green = '#913A45'
magenta = '#A0514F'
red = '#D3685B'
tabs = '#c3c3c4'
tabs-active = '#E0956E'
white = '#c3c3c4'
yellow = '#c3c3c4'
dim-black = '#0000008e'
dim-blue = '#6548478e'
dim-cyan = '#90363B8e'
dim-foreground = '#c3c3c48e'
dim-green = '#913A458e'
dim-magenta = '#A0514F8e'
dim-red = '#D3685B8e'
dim-white = '#E0956E8e'
dim-yellow = '#c3c3c48e'
light-black = '#654847'
light-blue = '#90363B'
light-cyan = '#913A45'
light-foreground = '#A0514F'
light-green = '#D3685B'
light-magenta = '#E0956E'
light-red = '#c3c3c4'
light-white = '#654847'
light-yellow = '#90363B'
