[colors.primary]
background = "#000000"
foreground = "#ddd1d8"

[colors.cursor]
text = "#000000"
cursor = "#ddd1d8"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ddd1d8"

[colors.search.matches]
foreground = "#000000"
background = "#ddd1d8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#a18d99"
background = "#ddd1d8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#B19CC5"
green = "#92ABD8"
yellow = "#AEB0D4"
blue = "#CB9DC2"
magenta = "#D0ADC8"
cyan = "#EFB3C5"
white = "#ddd1d8"

[colors.bright]
black = "#a18d99"
red = "#B19CC5"
green = "#92ABD8"
yellow = "#AEB0D4"
blue = "#CB9DC2"
magenta = "#D0ADC8"
cyan = "#EFB3C5"
white = "#ddd1d8"

[colors.dim]
black = "#ddd1d8"
red = "#B19CC5"
green = "#D0ADC8"
yellow = "#AEB0D4"
blue = "#CB9DC2"
magenta = "#92ABD8"
cyan = "#EFB3C5"
white = "#a18d99"

