[colors]
background = '#0000008e'
black = '#000000'
blue = '#506F93'
cursor = '#c6cfc8'
cyan = '#A66886'
foreground = '#c6cfc8'
green = '#619BA0'
magenta = '#49ACB7'
red = '#5FAADA'
tabs = '#c6cfc8'
tabs-active = '#97A69F'
white = '#c6cfc8'
yellow = '#c6cfc8'
dim-black = '#0000008e'
dim-blue = '#506F938e'
dim-cyan = '#A668868e'
dim-foreground = '#c6cfc88e'
dim-green = '#619BA08e'
dim-magenta = '#49ACB78e'
dim-red = '#5FAADA8e'
dim-white = '#97A69F8e'
dim-yellow = '#c6cfc88e'
light-black = '#506F93'
light-blue = '#A66886'
light-cyan = '#619BA0'
light-foreground = '#49ACB7'
light-green = '#5FAADA'
light-magenta = '#97A69F'
light-red = '#c6cfc8'
light-white = '#506F93'
light-yellow = '#A66886'
