[colors]
background = '#0000008e'
black = '#000000'
blue = '#ED6D4B'
cursor = '#c6c2c2'
cyan = '#E6B45F'
foreground = '#c6c2c2'
green = '#E5A161'
magenta = '#8E7F8D'
red = '#A9A096'
tabs = '#c6c2c2'
tabs-active = '#DFB689'
white = '#c6c2c2'
yellow = '#c6c2c2'
dim-black = '#0000008e'
dim-blue = '#ED6D4B8e'
dim-cyan = '#E6B45F8e'
dim-foreground = '#c6c2c28e'
dim-green = '#E5A1618e'
dim-magenta = '#8E7F8D8e'
dim-red = '#A9A0968e'
dim-white = '#DFB6898e'
dim-yellow = '#c6c2c28e'
light-black = '#ED6D4B'
light-blue = '#E6B45F'
light-cyan = '#E5A161'
light-foreground = '#8E7F8D'
light-green = '#A9A096'
light-magenta = '#DFB689'
light-red = '#c6c2c2'
light-white = '#ED6D4B'
light-yellow = '#E6B45F'
