[colors.primary]
background = "#000000"
foreground = "#c1c4c5"

[colors.cursor]
text = "#000000"
cursor = "#c1c4c5"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c1c4c5"

[colors.search.matches]
foreground = "#000000"
background = "#c1c4c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#596b6d"
background = "#c1c4c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#026958"
green = "#01536E"
yellow = "#01647B"
blue = "#028F76"
magenta = "#016988"
cyan = "#026799"
white = "#c1c4c5"

[colors.bright]
black = "#596b6d"
red = "#026958"
green = "#01536E"
yellow = "#01647B"
blue = "#028F76"
magenta = "#016988"
cyan = "#026799"
white = "#c1c4c5"

[colors.dim]
black = "#c1c4c5"
red = "#026958"
green = "#016988"
yellow = "#01647B"
blue = "#028F76"
magenta = "#01536E"
cyan = "#026799"
white = "#596b6d"

