[colors]
background = '#0000008e'
black = '#000000'
blue = '#1399AF'
cursor = '#c8cccc'
cyan = '#2C9FA9'
foreground = '#c8cccc'
green = '#62AFA6'
magenta = '#7EC1AE'
red = '#8BBCAA'
tabs = '#c8cccc'
tabs-active = '#C8AC8A'
white = '#c8cccc'
yellow = '#c8cccc'
dim-black = '#0000008e'
dim-blue = '#1399AF8e'
dim-cyan = '#2C9FA98e'
dim-foreground = '#c8cccc8e'
dim-green = '#62AFA68e'
dim-magenta = '#7EC1AE8e'
dim-red = '#8BBCAA8e'
dim-white = '#C8AC8A8e'
dim-yellow = '#c8cccc8e'
light-black = '#1399AF'
light-blue = '#2C9FA9'
light-cyan = '#62AFA6'
light-foreground = '#7EC1AE'
light-green = '#8BBCAA'
light-magenta = '#C8AC8A'
light-red = '#c8cccc'
light-white = '#1399AF'
light-yellow = '#2C9FA9'
