[colors.primary]
background = "#000000"
foreground = "#c2c3c7"

[colors.cursor]
text = "#000000"
cursor = "#c2c3c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c3c7"

[colors.search.matches]
foreground = "#000000"
background = "#c2c3c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6171"
background = "#c2c3c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#326698"
green = "#5D748C"
yellow = "#6E899A"
blue = "#4694A9"
magenta = "#96A0AA"
cyan = "#C8BEBA"
white = "#c2c3c7"

[colors.bright]
black = "#5c6171"
red = "#326698"
green = "#5D748C"
yellow = "#6E899A"
blue = "#4694A9"
magenta = "#96A0AA"
cyan = "#C8BEBA"
white = "#c2c3c7"

[colors.dim]
black = "#c2c3c7"
red = "#326698"
green = "#96A0AA"
yellow = "#6E899A"
blue = "#4694A9"
magenta = "#5D748C"
cyan = "#C8BEBA"
white = "#5c6171"

