[colors.primary]
background = "#000000"
foreground = "#c3c2c7"

[colors.cursor]
text = "#000000"
cursor = "#c3c2c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c2c7"

[colors.search.matches]
foreground = "#000000"
background = "#c3c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#615d72"
background = "#c3c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#573264"
green = "#684C68"
yellow = "#B55D5F"
blue = "#975B6A"
magenta = "#E6986F"
cyan = "#735787"
white = "#c3c2c7"

[colors.bright]
black = "#615d72"
red = "#573264"
green = "#684C68"
yellow = "#B55D5F"
blue = "#975B6A"
magenta = "#E6986F"
cyan = "#735787"
white = "#c3c2c7"

[colors.dim]
black = "#c3c2c7"
red = "#573264"
green = "#E6986F"
yellow = "#B55D5F"
blue = "#975B6A"
magenta = "#684C68"
cyan = "#735787"
white = "#615d72"

