[colors.primary]
background = "#000000"
foreground = "#c3c6c6"

[colors.cursor]
text = "#000000"
cursor = "#c3c6c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c6c6"

[colors.search.matches]
foreground = "#000000"
background = "#c3c6c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d716d"
background = "#c3c6c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#AB674E"
green = "#548654"
yellow = "#6B8D66"
blue = "#A0996D"
magenta = "#547588"
cyan = "#609BA5"
white = "#c3c6c6"

[colors.bright]
black = "#5d716d"
red = "#AB674E"
green = "#548654"
yellow = "#6B8D66"
blue = "#A0996D"
magenta = "#547588"
cyan = "#609BA5"
white = "#c3c6c6"

[colors.dim]
black = "#c3c6c6"
red = "#AB674E"
green = "#547588"
yellow = "#6B8D66"
blue = "#A0996D"
magenta = "#548654"
cyan = "#609BA5"
white = "#5d716d"

