[colors]
background = '#0000008e'
black = '#000000'
blue = '#274D90'
cursor = '#c3c4c8'
cyan = '#255197'
foreground = '#c3c4c8'
green = '#3469B3'
magenta = '#3A6AB6'
red = '#4868B3'
tabs = '#c3c4c8'
tabs-active = '#3AA0DC'
white = '#c3c4c8'
yellow = '#c3c4c8'
dim-black = '#0000008e'
dim-blue = '#274D908e'
dim-cyan = '#2551978e'
dim-foreground = '#c3c4c88e'
dim-green = '#3469B38e'
dim-magenta = '#3A6AB68e'
dim-red = '#4868B38e'
dim-white = '#3AA0DC8e'
dim-yellow = '#c3c4c88e'
light-black = '#274D90'
light-blue = '#255197'
light-cyan = '#3469B3'
light-foreground = '#3A6AB6'
light-green = '#4868B3'
light-magenta = '#3AA0DC'
light-red = '#c3c4c8'
light-white = '#274D90'
light-yellow = '#255197'
