[colors.primary]
background = "#000000"
foreground = "#c7cccd"

[colors.cursor]
text = "#000000"
cursor = "#c7cccd"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c7cccd"

[colors.search.matches]
foreground = "#000000"
background = "#c7cccd"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#697c81"
background = "#c7cccd"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#A891B5"
green = "#D5B6AB"
yellow = "#A1AED3"
blue = "#DAAFCC"
magenta = "#B1CEE4"
cyan = "#A0D3E6"
white = "#c7cccd"

[colors.bright]
black = "#697c81"
red = "#A891B5"
green = "#D5B6AB"
yellow = "#A1AED3"
blue = "#DAAFCC"
magenta = "#B1CEE4"
cyan = "#A0D3E6"
white = "#c7cccd"

[colors.dim]
black = "#c7cccd"
red = "#A891B5"
green = "#B1CEE4"
yellow = "#A1AED3"
blue = "#DAAFCC"
magenta = "#D5B6AB"
cyan = "#A0D3E6"
white = "#697c81"

