[colors]
background = '#0000008e'
black = '#000000'
blue = '#A891B5'
cursor = '#c7cccd'
cyan = '#D5B6AB'
foreground = '#c7cccd'
green = '#A1AED3'
magenta = '#DAAFCC'
red = '#B1CEE4'
tabs = '#c7cccd'
tabs-active = '#A0D3E6'
white = '#c7cccd'
yellow = '#c7cccd'
dim-black = '#0000008e'
dim-blue = '#A891B58e'
dim-cyan = '#D5B6AB8e'
dim-foreground = '#c7cccd8e'
dim-green = '#A1AED38e'
dim-magenta = '#DAAFCC8e'
dim-red = '#B1CEE48e'
dim-white = '#A0D3E68e'
dim-yellow = '#c7cccd8e'
light-black = '#A891B5'
light-blue = '#D5B6AB'
light-cyan = '#A1AED3'
light-foreground = '#DAAFCC'
light-green = '#B1CEE4'
light-magenta = '#A0D3E6'
light-red = '#c7cccd'
light-white = '#A891B5'
light-yellow = '#D5B6AB'
