[colors]
background = '#0000008e'
black = '#000000'
blue = '#0C6492'
cursor = '#c3c4c4'
cyan = '#0274AD'
foreground = '#c3c4c4'
green = '#627887'
magenta = '#977C85'
red = '#4C9CB5'
tabs = '#c3c4c4'
tabs-active = '#9A9E9E'
white = '#c3c4c4'
yellow = '#c3c4c4'
dim-black = '#0000008e'
dim-blue = '#0C64928e'
dim-cyan = '#0274AD8e'
dim-foreground = '#c3c4c48e'
dim-green = '#6278878e'
dim-magenta = '#977C858e'
dim-red = '#4C9CB58e'
dim-white = '#9A9E9E8e'
dim-yellow = '#c3c4c48e'
light-black = '#0C6492'
light-blue = '#0274AD'
light-cyan = '#627887'
light-foreground = '#977C85'
light-green = '#4C9CB5'
light-magenta = '#9A9E9E'
light-red = '#c3c4c4'
light-white = '#0C6492'
light-yellow = '#0274AD'
