[colors.primary]
background = "#000000"
foreground = "#c7c2c7"

[colors.cursor]
text = "#000000"
cursor = "#c7c2c7"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c7c2c7"

[colors.search.matches]
foreground = "#000000"
background = "#c7c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#715d71"
background = "#c7c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#C49171"
green = "#36548D"
yellow = "#636C90"
blue = "#9A7887"
magenta = "#C17F82"
cyan = "#6F92B2"
white = "#c7c2c7"

[colors.bright]
black = "#715d71"
red = "#C49171"
green = "#36548D"
yellow = "#636C90"
blue = "#9A7887"
magenta = "#C17F82"
cyan = "#6F92B2"
white = "#c7c2c7"

[colors.dim]
black = "#c7c2c7"
red = "#C49171"
green = "#C17F82"
yellow = "#636C90"
blue = "#9A7887"
magenta = "#36548D"
cyan = "#6F92B2"
white = "#715d71"

