[colors]
background = '#0000008e'
black = '#000000'
blue = '#5D92C3'
cursor = '#c5c5ca'
cyan = '#AE86A7'
foreground = '#c5c5ca'
green = '#E0929D'
magenta = '#FDD5AC'
red = '#A4B9D5'
tabs = '#c5c5ca'
tabs-active = '#DAD8DC'
white = '#c5c5ca'
yellow = '#c5c5ca'
dim-black = '#0000008e'
dim-blue = '#5D92C38e'
dim-cyan = '#AE86A78e'
dim-foreground = '#c5c5ca8e'
dim-green = '#E0929D8e'
dim-magenta = '#FDD5AC8e'
dim-red = '#A4B9D58e'
dim-white = '#DAD8DC8e'
dim-yellow = '#c5c5ca8e'
light-black = '#5D92C3'
light-blue = '#AE86A7'
light-cyan = '#E0929D'
light-foreground = '#FDD5AC'
light-green = '#A4B9D5'
light-magenta = '#DAD8DC'
light-red = '#c5c5ca'
light-white = '#5D92C3'
light-yellow = '#AE86A7'
