[colors]
background = '#0000008e'
black = '#000000'
blue = '#4A5BAB'
cursor = '#c4c5cc'
cyan = '#5677C7'
foreground = '#c4c5cc'
green = '#8579C4'
magenta = '#6894DE'
red = '#77C2F9'
tabs = '#c4c5cc'
tabs-active = '#98ABEE'
white = '#c4c5cc'
yellow = '#c4c5cc'
dim-black = '#0000008e'
dim-blue = '#4A5BAB8e'
dim-cyan = '#5677C78e'
dim-foreground = '#c4c5cc8e'
dim-green = '#8579C48e'
dim-magenta = '#6894DE8e'
dim-red = '#77C2F98e'
dim-white = '#98ABEE8e'
dim-yellow = '#c4c5cc8e'
light-black = '#4A5BAB'
light-blue = '#5677C7'
light-cyan = '#8579C4'
light-foreground = '#6894DE'
light-green = '#77C2F9'
light-magenta = '#98ABEE'
light-red = '#c4c5cc'
light-white = '#4A5BAB'
light-yellow = '#5677C7'
