[colors.primary]
background = "#000000"
foreground = "#c2c3c5"

[colors.cursor]
text = "#000000"
cursor = "#c2c3c5"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c3c5"

[colors.search.matches]
foreground = "#000000"
background = "#c2c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a636e"
background = "#c2c3c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#344871"
green = "#4F516E"
yellow = "#37518C"
blue = "#4B55A0"
magenta = "#5468A0"
cyan = "#906983"
white = "#c2c3c5"

[colors.bright]
black = "#5a636e"
red = "#344871"
green = "#4F516E"
yellow = "#37518C"
blue = "#4B55A0"
magenta = "#5468A0"
cyan = "#906983"
white = "#c2c3c5"

[colors.dim]
black = "#c2c3c5"
red = "#344871"
green = "#5468A0"
yellow = "#37518C"
blue = "#4B55A0"
magenta = "#4F516E"
cyan = "#906983"
white = "#5a636e"

