[colors.primary]
background = "#000000"
foreground = "#c2c4c6"

[colors.cursor]
text = "#000000"
cursor = "#c2c4c6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c2c4c6"

[colors.search.matches]
foreground = "#000000"
background = "#c2c4c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6370"
background = "#c2c4c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#615453"
green = "#A25836"
yellow = "#9E6B4F"
blue = "#D9A058"
magenta = "#D6B760"
cyan = "#7A7581"
white = "#c2c4c6"

[colors.bright]
black = "#5c6370"
red = "#615453"
green = "#A25836"
yellow = "#9E6B4F"
blue = "#D9A058"
magenta = "#D6B760"
cyan = "#7A7581"
white = "#c2c4c6"

[colors.dim]
black = "#c2c4c6"
red = "#615453"
green = "#D6B760"
yellow = "#9E6B4F"
blue = "#D9A058"
magenta = "#A25836"
cyan = "#7A7581"
white = "#5c6370"

