[colors]
background = '#0000008e'
black = '#000000'
blue = '#675D62'
cursor = '#c2c3c6'
cyan = '#916A62'
foreground = '#c2c3c6'
green = '#C17347'
magenta = '#D6A960'
red = '#5C7086'
tabs = '#c2c3c6'
tabs-active = '#7D8189'
white = '#c2c3c6'
yellow = '#c2c3c6'
dim-black = '#0000008e'
dim-blue = '#675D628e'
dim-cyan = '#916A628e'
dim-foreground = '#c2c3c68e'
dim-green = '#C173478e'
dim-magenta = '#D6A9608e'
dim-red = '#5C70868e'
dim-white = '#7D81898e'
dim-yellow = '#c2c3c68e'
light-black = '#675D62'
light-blue = '#916A62'
light-cyan = '#C17347'
light-foreground = '#D6A960'
light-green = '#5C7086'
light-magenta = '#7D8189'
light-red = '#c2c3c6'
light-white = '#675D62'
light-yellow = '#916A62'
