[colors]
background = '#0000008e'
black = '#000000'
blue = '#505065'
cursor = '#c1c1c5'
cyan = '#535267'
foreground = '#c1c1c5'
green = '#6E6678'
magenta = '#82727C'
red = '#7D7181'
tabs = '#c1c1c5'
tabs-active = '#887988'
white = '#c1c1c5'
yellow = '#c1c1c5'
dim-black = '#0000008e'
dim-blue = '#5050658e'
dim-cyan = '#5352678e'
dim-foreground = '#c1c1c58e'
dim-green = '#6E66788e'
dim-magenta = '#82727C8e'
dim-red = '#7D71818e'
dim-white = '#8879888e'
dim-yellow = '#c1c1c58e'
light-black = '#505065'
light-blue = '#535267'
light-cyan = '#6E6678'
light-foreground = '#82727C'
light-green = '#7D7181'
light-magenta = '#887988'
light-red = '#c1c1c5'
light-white = '#505065'
light-yellow = '#535267'
