[colors.primary]
background = "#000000"
foreground = "#c6c3c2"

[colors.cursor]
text = "#000000"
cursor = "#c6c3c2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c6c3c2"

[colors.search.matches]
foreground = "#000000"
background = "#c6c3c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#70615b"
background = "#c6c3c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#D96829"
green = "#AB7251"
yellow = "#DB9B58"
blue = "#EBB65B"
magenta = "#987F80"
cyan = "#C7A99F"
white = "#c6c3c2"

[colors.bright]
black = "#70615b"
red = "#D96829"
green = "#AB7251"
yellow = "#DB9B58"
blue = "#EBB65B"
magenta = "#987F80"
cyan = "#C7A99F"
white = "#c6c3c2"

[colors.dim]
black = "#c6c3c2"
red = "#D96829"
green = "#987F80"
yellow = "#DB9B58"
blue = "#EBB65B"
magenta = "#AB7251"
cyan = "#C7A99F"
white = "#70615b"

