[colors.primary]
background = "#000000"
foreground = "#c3c1c1"

[colors.cursor]
text = "#000000"
cursor = "#c3c1c1"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c1c1"

[colors.search.matches]
foreground = "#000000"
background = "#c3c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a5a57"
background = "#c3c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#BB4446"
green = "#EC665B"
yellow = "#AB8975"
blue = "#F9946D"
magenta = "#F75B8F"
cyan = "#F4A897"
white = "#c3c1c1"

[colors.bright]
black = "#6a5a57"
red = "#BB4446"
green = "#EC665B"
yellow = "#AB8975"
blue = "#F9946D"
magenta = "#F75B8F"
cyan = "#F4A897"
white = "#c3c1c1"

[colors.dim]
black = "#c3c1c1"
red = "#BB4446"
green = "#F75B8F"
yellow = "#AB8975"
blue = "#F9946D"
magenta = "#EC665B"
cyan = "#F4A897"
white = "#6a5a57"

