--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bjtn/.config/wallpapers/wallhaven-jxl56w_1920x1080.png"

-- Special
background="#000000"
foreground="#c5c7c7"
cursor="#c5c7c7"

-- Colors
color0="#000000"
color1="#6AC5AD"
color2="#95A8A4"
color3="#9ED4A3"
color4="#D6D89D"
color5="#94B7CF"
color6="#95CDCD"
color7="#c5c7c7"
color8="#607572"
color9="#6AC5AD"
color10="#95A8A4"
color11="#9ED4A3"
color12="#D6D89D"
color13="#94B7CF"
color14="#95CDCD"
color15="#c5c7c7"
