[colors]
background = '#0000008e'
black = '#000000'
blue = '#4B95AE'
cursor = '#c6caca'
cyan = '#57A4A8'
foreground = '#c6caca'
green = '#9CACA2'
magenta = '#E5ACA1'
red = '#A8C8AA'
tabs = '#c6caca'
tabs-active = '#DDCDB2'
white = '#c6caca'
yellow = '#c6caca'
dim-black = '#0000008e'
dim-blue = '#4B95AE8e'
dim-cyan = '#57A4A88e'
dim-foreground = '#c6caca8e'
dim-green = '#9CACA28e'
dim-magenta = '#E5ACA18e'
dim-red = '#A8C8AA8e'
dim-white = '#DDCDB28e'
dim-yellow = '#c6caca8e'
light-black = '#4B95AE'
light-blue = '#57A4A8'
light-cyan = '#9CACA2'
light-foreground = '#E5ACA1'
light-green = '#A8C8AA'
light-magenta = '#DDCDB2'
light-red = '#c6caca'
light-white = '#4B95AE'
light-yellow = '#57A4A8'
