[colors.primary]
background = "#000000"
foreground = "#c4c5cc"

[colors.cursor]
text = "#000000"
cursor = "#c4c5cc"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c4c5cc"

[colors.search.matches]
foreground = "#000000"
background = "#c4c5cc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#65677c"
background = "#c4c5cc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#4A5BAB"
green = "#5677C7"
yellow = "#8579C4"
blue = "#6894DE"
magenta = "#77C2F9"
cyan = "#98ABEE"
white = "#c4c5cc"

[colors.bright]
black = "#65677c"
red = "#4A5BAB"
green = "#5677C7"
yellow = "#8579C4"
blue = "#6894DE"
magenta = "#77C2F9"
cyan = "#98ABEE"
white = "#c4c5cc"

[colors.dim]
black = "#c4c5cc"
red = "#4A5BAB"
green = "#77C2F9"
yellow = "#8579C4"
blue = "#6894DE"
magenta = "#5677C7"
cyan = "#98ABEE"
white = "#65677c"

