[colors]
background = '#0000008e'
black = '#000000'
blue = '#8F725A'
cursor = '#c7c3c2'
cyan = '#7C8476'
foreground = '#c7c3c2'
green = '#A1886E'
magenta = '#CDA272'
red = '#A0A49A'
tabs = '#c7c3c2'
tabs-active = '#D0BA98'
white = '#c7c3c2'
yellow = '#c7c3c2'
dim-black = '#0000008e'
dim-blue = '#8F725A8e'
dim-cyan = '#7C84768e'
dim-foreground = '#c7c3c28e'
dim-green = '#A1886E8e'
dim-magenta = '#CDA2728e'
dim-red = '#A0A49A8e'
dim-white = '#D0BA988e'
dim-yellow = '#c7c3c28e'
light-black = '#8F725A'
light-blue = '#7C8476'
light-cyan = '#A1886E'
light-foreground = '#CDA272'
light-green = '#A0A49A'
light-magenta = '#D0BA98'
light-red = '#c7c3c2'
light-white = '#8F725A'
light-yellow = '#7C8476'
