[colors]
background = '#0000008e'
black = '#000000'
blue = '#B7867B'
cursor = '#c3c2c6'
cyan = '#736C8B'
foreground = '#c3c2c6'
green = '#8F7596'
magenta = '#A07692'
red = '#CA7984'
tabs = '#c3c2c6'
tabs-active = '#A3869A'
white = '#c3c2c6'
yellow = '#c3c2c6'
dim-black = '#0000008e'
dim-blue = '#B7867B8e'
dim-cyan = '#736C8B8e'
dim-foreground = '#c3c2c68e'
dim-green = '#8F75968e'
dim-magenta = '#A076928e'
dim-red = '#CA79848e'
dim-white = '#A3869A8e'
dim-yellow = '#c3c2c68e'
light-black = '#B7867B'
light-blue = '#736C8B'
light-cyan = '#8F7596'
light-foreground = '#A07692'
light-green = '#CA7984'
light-magenta = '#A3869A'
light-red = '#c3c2c6'
light-white = '#B7867B'
light-yellow = '#736C8B'
