[colors]
background = '#0000008e'
black = '#000000'
blue = '#296993'
cursor = '#c3c4c8'
cyan = '#2273BF'
foreground = '#c3c4c8'
green = '#596EA2'
magenta = '#A277A1'
red = '#358AB4'
tabs = '#c3c4c8'
tabs-active = '#37A2CB'
white = '#c3c4c8'
yellow = '#c3c4c8'
dim-black = '#0000008e'
dim-blue = '#2969938e'
dim-cyan = '#2273BF8e'
dim-foreground = '#c3c4c88e'
dim-green = '#596EA28e'
dim-magenta = '#A277A18e'
dim-red = '#358AB48e'
dim-white = '#37A2CB8e'
dim-yellow = '#c3c4c88e'
light-black = '#296993'
light-blue = '#2273BF'
light-cyan = '#596EA2'
light-foreground = '#A277A1'
light-green = '#358AB4'
light-magenta = '#37A2CB'
light-red = '#c3c4c8'
light-white = '#296993'
light-yellow = '#2273BF'
