[colors.primary]
background = "#000000"
foreground = "#cacbcf"

[colors.cursor]
text = "#000000"
cursor = "#cacbcf"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#cacbcf"

[colors.search.matches]
foreground = "#000000"
background = "#cacbcf"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6f7687"
background = "#cacbcf"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#3496C5"
green = "#17ADD2"
yellow = "#2CAFCF"
blue = "#4CB5CD"
magenta = "#EA9194"
cyan = "#E8A69F"
white = "#cacbcf"

[colors.bright]
black = "#6f7687"
red = "#3496C5"
green = "#17ADD2"
yellow = "#2CAFCF"
blue = "#4CB5CD"
magenta = "#EA9194"
cyan = "#E8A69F"
white = "#cacbcf"

[colors.dim]
black = "#cacbcf"
red = "#3496C5"
green = "#EA9194"
yellow = "#2CAFCF"
blue = "#4CB5CD"
magenta = "#17ADD2"
cyan = "#E8A69F"
white = "#6f7687"

