[colors.primary]
background = "#000000"
foreground = "#c3c9c9"

[colors.cursor]
text = "#000000"
cursor = "#c3c9c9"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c9c9"

[colors.search.matches]
foreground = "#000000"
background = "#c3c9c9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#607676"
background = "#c3c9c9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#BDCA51"
green = "#F3E76C"
yellow = "#096B95"
blue = "#1D949C"
magenta = "#23B0DE"
cyan = "#4DC3CF"
white = "#c3c9c9"

[colors.bright]
black = "#607676"
red = "#BDCA51"
green = "#F3E76C"
yellow = "#096B95"
blue = "#1D949C"
magenta = "#23B0DE"
cyan = "#4DC3CF"
white = "#c3c9c9"

[colors.dim]
black = "#c3c9c9"
red = "#BDCA51"
green = "#23B0DE"
yellow = "#096B95"
blue = "#1D949C"
magenta = "#F3E76C"
cyan = "#4DC3CF"
white = "#607676"

