[colors.primary]
background = "#000000"
foreground = "#c5c8cd"

[colors.cursor]
text = "#000000"
cursor = "#c5c8cd"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c5c8cd"

[colors.search.matches]
foreground = "#000000"
background = "#c5c8cd"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#67707e"
background = "#c5c8cd"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#3478CA"
green = "#437CC5"
yellow = "#917593"
blue = "#3A88DB"
magenta = "#488AD5"
cyan = "#53A2E7"
white = "#c5c8cd"

[colors.bright]
black = "#67707e"
red = "#3478CA"
green = "#437CC5"
yellow = "#917593"
blue = "#3A88DB"
magenta = "#488AD5"
cyan = "#53A2E7"
white = "#c5c8cd"

[colors.dim]
black = "#c5c8cd"
red = "#3478CA"
green = "#488AD5"
yellow = "#917593"
blue = "#3A88DB"
magenta = "#437CC5"
cyan = "#53A2E7"
white = "#67707e"

