[colors]
background = '#0000008e'
black = '#000000'
blue = '#3496C5'
cursor = '#cacbcf'
cyan = '#17ADD2'
foreground = '#cacbcf'
green = '#2CAFCF'
magenta = '#4CB5CD'
red = '#EA9194'
tabs = '#cacbcf'
tabs-active = '#E8A69F'
white = '#cacbcf'
yellow = '#cacbcf'
dim-black = '#0000008e'
dim-blue = '#3496C58e'
dim-cyan = '#17ADD28e'
dim-foreground = '#cacbcf8e'
dim-green = '#2CAFCF8e'
dim-magenta = '#4CB5CD8e'
dim-red = '#EA91948e'
dim-white = '#E8A69F8e'
dim-yellow = '#cacbcf8e'
light-black = '#3496C5'
light-blue = '#17ADD2'
light-cyan = '#2CAFCF'
light-foreground = '#4CB5CD'
light-green = '#EA9194'
light-magenta = '#E8A69F'
light-red = '#cacbcf'
light-white = '#3496C5'
light-yellow = '#17ADD2'
