[colors]
background = '#0000008e'
black = '#000000'
blue = '#BFAA3B'
cursor = '#c4c5cc'
cyan = '#DFA923'
foreground = '#c4c5cc'
green = '#2451AF'
magenta = '#57689B'
red = '#5E9FD5'
tabs = '#c4c5cc'
tabs-active = '#44ADCA'
white = '#c4c5cc'
yellow = '#c4c5cc'
dim-black = '#0000008e'
dim-blue = '#BFAA3B8e'
dim-cyan = '#DFA9238e'
dim-foreground = '#c4c5cc8e'
dim-green = '#2451AF8e'
dim-magenta = '#57689B8e'
dim-red = '#5E9FD58e'
dim-white = '#44ADCA8e'
dim-yellow = '#c4c5cc8e'
light-black = '#BFAA3B'
light-blue = '#DFA923'
light-cyan = '#2451AF'
light-foreground = '#57689B'
light-green = '#5E9FD5'
light-magenta = '#44ADCA'
light-red = '#c4c5cc'
light-white = '#BFAA3B'
light-yellow = '#DFA923'
