[colors]
background = '#0000008e'
black = '#000000'
blue = '#71CAE4'
cursor = '#c8cbcf'
cyan = '#A0A2A7'
foreground = '#c8cbcf'
green = '#E0B0A5'
magenta = '#F1CFA7'
red = '#BABAC3'
tabs = '#c8cbcf'
tabs-active = '#A2CFE5'
white = '#c8cbcf'
yellow = '#c8cbcf'
dim-black = '#0000008e'
dim-blue = '#71CAE48e'
dim-cyan = '#A0A2A78e'
dim-foreground = '#c8cbcf8e'
dim-green = '#E0B0A58e'
dim-magenta = '#F1CFA78e'
dim-red = '#BABAC38e'
dim-white = '#A2CFE58e'
dim-yellow = '#c8cbcf8e'
light-black = '#71CAE4'
light-blue = '#A0A2A7'
light-cyan = '#E0B0A5'
light-foreground = '#F1CFA7'
light-green = '#BABAC3'
light-magenta = '#A2CFE5'
light-red = '#c8cbcf'
light-white = '#71CAE4'
light-yellow = '#A0A2A7'
