# pywal theme for ghostty

background = 000000
foreground = c4c4ca
cursor-color = c4c4ca
selection-background = c4c4ca
selection-foreground = 000000

palette = 0=#000000
palette = 1=#863D6F
palette = 2=#9B4878
palette = 3=#AF5887
palette = 4=#A17E82
palette = 5=#D26491
palette = 6=#F29DB0
palette = 7=#c4c4ca
palette = 8=#646379
palette = 9=#863D6F
palette = 10=#9B4878
palette = 11=#AF5887
palette = 12=#A17E82
palette = 13=#D26491
palette = 14=#F29DB0
palette = 15=#c4c4ca
