# pywal theme for ghostty

background = 000000
foreground = c7c2c3
cursor-color = c7c2c3
selection-background = c7c2c3
selection-foreground = 000000

palette = 0=#000000
palette = 1=#E27051
palette = 2=#F09863
palette = 3=#F6CA40
palette = 4=#AC6F87
palette = 5=#B29C9F
palette = 6=#EDAB92
palette = 7=#c7c2c3
palette = 8=#725d5f
palette = 9=#E27051
palette = 10=#F09863
palette = 11=#F6CA40
palette = 12=#AC6F87
palette = 13=#B29C9F
palette = 14=#EDAB92
palette = 15=#c7c2c3
